# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0

import ttnn
import model_pt
import utils


ROW_MAJOR_BFLOAT16_WEIGHTS = {
    "L__self___model_embed_tokens.weight",
    "L__self___model_layers_0_self_attn_k_proj.weight",
    "L__self___model_layers_0_self_attn_q_proj.weight",
    "L__self___model_layers_0_self_attn_v_proj.weight",
    "L__self___model_layers_10_self_attn_k_proj.weight",
    "L__self___model_layers_10_self_attn_q_proj.weight",
    "L__self___model_layers_10_self_attn_v_proj.weight",
    "L__self___model_layers_11_self_attn_k_proj.weight",
    "L__self___model_layers_11_self_attn_q_proj.weight",
    "L__self___model_layers_11_self_attn_v_proj.weight",
    "L__self___model_layers_12_self_attn_k_proj.weight",
    "L__self___model_layers_12_self_attn_q_proj.weight",
    "L__self___model_layers_12_self_attn_v_proj.weight",
    "L__self___model_layers_13_self_attn_k_proj.weight",
    "L__self___model_layers_13_self_attn_q_proj.weight",
    "L__self___model_layers_13_self_attn_v_proj.weight",
    "L__self___model_layers_14_self_attn_k_proj.weight",
    "L__self___model_layers_14_self_attn_q_proj.weight",
    "L__self___model_layers_14_self_attn_v_proj.weight",
    "L__self___model_layers_15_self_attn_k_proj.weight",
    "L__self___model_layers_15_self_attn_q_proj.weight",
    "L__self___model_layers_15_self_attn_v_proj.weight",
    "L__self___model_layers_16_self_attn_k_proj.weight",
    "L__self___model_layers_16_self_attn_q_proj.weight",
    "L__self___model_layers_16_self_attn_v_proj.weight",
    "L__self___model_layers_17_self_attn_k_proj.weight",
    "L__self___model_layers_17_self_attn_q_proj.weight",
    "L__self___model_layers_17_self_attn_v_proj.weight",
    "L__self___model_layers_18_self_attn_k_proj.weight",
    "L__self___model_layers_18_self_attn_q_proj.weight",
    "L__self___model_layers_18_self_attn_v_proj.weight",
    "L__self___model_layers_19_self_attn_k_proj.weight",
    "L__self___model_layers_19_self_attn_q_proj.weight",
    "L__self___model_layers_19_self_attn_v_proj.weight",
    "L__self___model_layers_1_self_attn_k_proj.weight",
    "L__self___model_layers_1_self_attn_q_proj.weight",
    "L__self___model_layers_1_self_attn_v_proj.weight",
    "L__self___model_layers_20_self_attn_k_proj.weight",
    "L__self___model_layers_20_self_attn_q_proj.weight",
    "L__self___model_layers_20_self_attn_v_proj.weight",
    "L__self___model_layers_21_self_attn_k_proj.weight",
    "L__self___model_layers_21_self_attn_q_proj.weight",
    "L__self___model_layers_21_self_attn_v_proj.weight",
    "L__self___model_layers_22_self_attn_k_proj.weight",
    "L__self___model_layers_22_self_attn_q_proj.weight",
    "L__self___model_layers_22_self_attn_v_proj.weight",
    "L__self___model_layers_23_self_attn_k_proj.weight",
    "L__self___model_layers_23_self_attn_q_proj.weight",
    "L__self___model_layers_23_self_attn_v_proj.weight",
    "L__self___model_layers_24_self_attn_k_proj.weight",
    "L__self___model_layers_24_self_attn_q_proj.weight",
    "L__self___model_layers_24_self_attn_v_proj.weight",
    "L__self___model_layers_25_self_attn_k_proj.weight",
    "L__self___model_layers_25_self_attn_q_proj.weight",
    "L__self___model_layers_25_self_attn_v_proj.weight",
    "L__self___model_layers_26_self_attn_k_proj.weight",
    "L__self___model_layers_26_self_attn_q_proj.weight",
    "L__self___model_layers_26_self_attn_v_proj.weight",
    "L__self___model_layers_27_self_attn_k_proj.weight",
    "L__self___model_layers_27_self_attn_q_proj.weight",
    "L__self___model_layers_27_self_attn_v_proj.weight",
    "L__self___model_layers_28_self_attn_k_proj.weight",
    "L__self___model_layers_28_self_attn_q_proj.weight",
    "L__self___model_layers_28_self_attn_v_proj.weight",
    "L__self___model_layers_29_self_attn_k_proj.weight",
    "L__self___model_layers_29_self_attn_q_proj.weight",
    "L__self___model_layers_29_self_attn_v_proj.weight",
    "L__self___model_layers_2_self_attn_k_proj.weight",
    "L__self___model_layers_2_self_attn_q_proj.weight",
    "L__self___model_layers_2_self_attn_v_proj.weight",
    "L__self___model_layers_30_self_attn_k_proj.weight",
    "L__self___model_layers_30_self_attn_q_proj.weight",
    "L__self___model_layers_30_self_attn_v_proj.weight",
    "L__self___model_layers_31_self_attn_k_proj.weight",
    "L__self___model_layers_31_self_attn_q_proj.weight",
    "L__self___model_layers_31_self_attn_v_proj.weight",
    "L__self___model_layers_32_self_attn_k_proj.weight",
    "L__self___model_layers_32_self_attn_q_proj.weight",
    "L__self___model_layers_32_self_attn_v_proj.weight",
    "L__self___model_layers_33_self_attn_k_proj.weight",
    "L__self___model_layers_33_self_attn_q_proj.weight",
    "L__self___model_layers_33_self_attn_v_proj.weight",
    "L__self___model_layers_34_self_attn_k_proj.weight",
    "L__self___model_layers_34_self_attn_q_proj.weight",
    "L__self___model_layers_34_self_attn_v_proj.weight",
    "L__self___model_layers_35_self_attn_k_proj.weight",
    "L__self___model_layers_35_self_attn_q_proj.weight",
    "L__self___model_layers_35_self_attn_v_proj.weight",
    "L__self___model_layers_3_self_attn_k_proj.weight",
    "L__self___model_layers_3_self_attn_q_proj.weight",
    "L__self___model_layers_3_self_attn_v_proj.weight",
    "L__self___model_layers_4_self_attn_k_proj.weight",
    "L__self___model_layers_4_self_attn_q_proj.weight",
    "L__self___model_layers_4_self_attn_v_proj.weight",
    "L__self___model_layers_5_self_attn_k_proj.weight",
    "L__self___model_layers_5_self_attn_q_proj.weight",
    "L__self___model_layers_5_self_attn_v_proj.weight",
    "L__self___model_layers_6_self_attn_k_proj.weight",
    "L__self___model_layers_6_self_attn_q_proj.weight",
    "L__self___model_layers_6_self_attn_v_proj.weight",
    "L__self___model_layers_7_self_attn_k_proj.weight",
    "L__self___model_layers_7_self_attn_q_proj.weight",
    "L__self___model_layers_7_self_attn_v_proj.weight",
    "L__self___model_layers_8_self_attn_k_proj.weight",
    "L__self___model_layers_8_self_attn_q_proj.weight",
    "L__self___model_layers_8_self_attn_v_proj.weight",
    "L__self___model_layers_9_self_attn_k_proj.weight",
    "L__self___model_layers_9_self_attn_q_proj.weight",
    "L__self___model_layers_9_self_attn_v_proj.weight",
}


TILE_BFLOAT16_WEIGHTS = {
    "L__self___lm_head.weight",
    "L__self___model_layers_0_input_layernorm_weight",
    "L__self___model_layers_0_mlp_down_proj.weight",
    "L__self___model_layers_0_mlp_gate_proj.weight",
    "L__self___model_layers_0_mlp_up_proj.weight",
    "L__self___model_layers_0_post_attention_layernorm_weight",
    "L__self___model_layers_0_self_attn_k_norm_weight",
    "L__self___model_layers_0_self_attn_o_proj.weight",
    "L__self___model_layers_0_self_attn_q_norm_weight",
    "L__self___model_layers_10_input_layernorm_weight",
    "L__self___model_layers_10_mlp_down_proj.weight",
    "L__self___model_layers_10_mlp_gate_proj.weight",
    "L__self___model_layers_10_mlp_up_proj.weight",
    "L__self___model_layers_10_post_attention_layernorm_weight",
    "L__self___model_layers_10_self_attn_k_norm_weight",
    "L__self___model_layers_10_self_attn_o_proj.weight",
    "L__self___model_layers_10_self_attn_q_norm_weight",
    "L__self___model_layers_11_input_layernorm_weight",
    "L__self___model_layers_11_mlp_down_proj.weight",
    "L__self___model_layers_11_mlp_gate_proj.weight",
    "L__self___model_layers_11_mlp_up_proj.weight",
    "L__self___model_layers_11_post_attention_layernorm_weight",
    "L__self___model_layers_11_self_attn_k_norm_weight",
    "L__self___model_layers_11_self_attn_o_proj.weight",
    "L__self___model_layers_11_self_attn_q_norm_weight",
    "L__self___model_layers_12_input_layernorm_weight",
    "L__self___model_layers_12_mlp_down_proj.weight",
    "L__self___model_layers_12_mlp_gate_proj.weight",
    "L__self___model_layers_12_mlp_up_proj.weight",
    "L__self___model_layers_12_post_attention_layernorm_weight",
    "L__self___model_layers_12_self_attn_k_norm_weight",
    "L__self___model_layers_12_self_attn_o_proj.weight",
    "L__self___model_layers_12_self_attn_q_norm_weight",
    "L__self___model_layers_13_input_layernorm_weight",
    "L__self___model_layers_13_mlp_down_proj.weight",
    "L__self___model_layers_13_mlp_gate_proj.weight",
    "L__self___model_layers_13_mlp_up_proj.weight",
    "L__self___model_layers_13_post_attention_layernorm_weight",
    "L__self___model_layers_13_self_attn_k_norm_weight",
    "L__self___model_layers_13_self_attn_o_proj.weight",
    "L__self___model_layers_13_self_attn_q_norm_weight",
    "L__self___model_layers_14_input_layernorm_weight",
    "L__self___model_layers_14_mlp_down_proj.weight",
    "L__self___model_layers_14_mlp_gate_proj.weight",
    "L__self___model_layers_14_mlp_up_proj.weight",
    "L__self___model_layers_14_post_attention_layernorm_weight",
    "L__self___model_layers_14_self_attn_k_norm_weight",
    "L__self___model_layers_14_self_attn_o_proj.weight",
    "L__self___model_layers_14_self_attn_q_norm_weight",
    "L__self___model_layers_15_input_layernorm_weight",
    "L__self___model_layers_15_mlp_down_proj.weight",
    "L__self___model_layers_15_mlp_gate_proj.weight",
    "L__self___model_layers_15_mlp_up_proj.weight",
    "L__self___model_layers_15_post_attention_layernorm_weight",
    "L__self___model_layers_15_self_attn_k_norm_weight",
    "L__self___model_layers_15_self_attn_o_proj.weight",
    "L__self___model_layers_15_self_attn_q_norm_weight",
    "L__self___model_layers_16_input_layernorm_weight",
    "L__self___model_layers_16_mlp_down_proj.weight",
    "L__self___model_layers_16_mlp_gate_proj.weight",
    "L__self___model_layers_16_mlp_up_proj.weight",
    "L__self___model_layers_16_post_attention_layernorm_weight",
    "L__self___model_layers_16_self_attn_k_norm_weight",
    "L__self___model_layers_16_self_attn_o_proj.weight",
    "L__self___model_layers_16_self_attn_q_norm_weight",
    "L__self___model_layers_17_input_layernorm_weight",
    "L__self___model_layers_17_mlp_down_proj.weight",
    "L__self___model_layers_17_mlp_gate_proj.weight",
    "L__self___model_layers_17_mlp_up_proj.weight",
    "L__self___model_layers_17_post_attention_layernorm_weight",
    "L__self___model_layers_17_self_attn_k_norm_weight",
    "L__self___model_layers_17_self_attn_o_proj.weight",
    "L__self___model_layers_17_self_attn_q_norm_weight",
    "L__self___model_layers_18_input_layernorm_weight",
    "L__self___model_layers_18_mlp_down_proj.weight",
    "L__self___model_layers_18_mlp_gate_proj.weight",
    "L__self___model_layers_18_mlp_up_proj.weight",
    "L__self___model_layers_18_post_attention_layernorm_weight",
    "L__self___model_layers_18_self_attn_k_norm_weight",
    "L__self___model_layers_18_self_attn_o_proj.weight",
    "L__self___model_layers_18_self_attn_q_norm_weight",
    "L__self___model_layers_19_input_layernorm_weight",
    "L__self___model_layers_19_mlp_down_proj.weight",
    "L__self___model_layers_19_mlp_gate_proj.weight",
    "L__self___model_layers_19_mlp_up_proj.weight",
    "L__self___model_layers_19_post_attention_layernorm_weight",
    "L__self___model_layers_19_self_attn_k_norm_weight",
    "L__self___model_layers_19_self_attn_o_proj.weight",
    "L__self___model_layers_19_self_attn_q_norm_weight",
    "L__self___model_layers_1_input_layernorm_weight",
    "L__self___model_layers_1_mlp_down_proj.weight",
    "L__self___model_layers_1_mlp_gate_proj.weight",
    "L__self___model_layers_1_mlp_up_proj.weight",
    "L__self___model_layers_1_post_attention_layernorm_weight",
    "L__self___model_layers_1_self_attn_k_norm_weight",
    "L__self___model_layers_1_self_attn_o_proj.weight",
    "L__self___model_layers_1_self_attn_q_norm_weight",
    "L__self___model_layers_20_input_layernorm_weight",
    "L__self___model_layers_20_mlp_down_proj.weight",
    "L__self___model_layers_20_mlp_gate_proj.weight",
    "L__self___model_layers_20_mlp_up_proj.weight",
    "L__self___model_layers_20_post_attention_layernorm_weight",
    "L__self___model_layers_20_self_attn_k_norm_weight",
    "L__self___model_layers_20_self_attn_o_proj.weight",
    "L__self___model_layers_20_self_attn_q_norm_weight",
    "L__self___model_layers_21_input_layernorm_weight",
    "L__self___model_layers_21_mlp_down_proj.weight",
    "L__self___model_layers_21_mlp_gate_proj.weight",
    "L__self___model_layers_21_mlp_up_proj.weight",
    "L__self___model_layers_21_post_attention_layernorm_weight",
    "L__self___model_layers_21_self_attn_k_norm_weight",
    "L__self___model_layers_21_self_attn_o_proj.weight",
    "L__self___model_layers_21_self_attn_q_norm_weight",
    "L__self___model_layers_22_input_layernorm_weight",
    "L__self___model_layers_22_mlp_down_proj.weight",
    "L__self___model_layers_22_mlp_gate_proj.weight",
    "L__self___model_layers_22_mlp_up_proj.weight",
    "L__self___model_layers_22_post_attention_layernorm_weight",
    "L__self___model_layers_22_self_attn_k_norm_weight",
    "L__self___model_layers_22_self_attn_o_proj.weight",
    "L__self___model_layers_22_self_attn_q_norm_weight",
    "L__self___model_layers_23_input_layernorm_weight",
    "L__self___model_layers_23_mlp_down_proj.weight",
    "L__self___model_layers_23_mlp_gate_proj.weight",
    "L__self___model_layers_23_mlp_up_proj.weight",
    "L__self___model_layers_23_post_attention_layernorm_weight",
    "L__self___model_layers_23_self_attn_k_norm_weight",
    "L__self___model_layers_23_self_attn_o_proj.weight",
    "L__self___model_layers_23_self_attn_q_norm_weight",
    "L__self___model_layers_24_input_layernorm_weight",
    "L__self___model_layers_24_mlp_down_proj.weight",
    "L__self___model_layers_24_mlp_gate_proj.weight",
    "L__self___model_layers_24_mlp_up_proj.weight",
    "L__self___model_layers_24_post_attention_layernorm_weight",
    "L__self___model_layers_24_self_attn_k_norm_weight",
    "L__self___model_layers_24_self_attn_o_proj.weight",
    "L__self___model_layers_24_self_attn_q_norm_weight",
    "L__self___model_layers_25_input_layernorm_weight",
    "L__self___model_layers_25_mlp_down_proj.weight",
    "L__self___model_layers_25_mlp_gate_proj.weight",
    "L__self___model_layers_25_mlp_up_proj.weight",
    "L__self___model_layers_25_post_attention_layernorm_weight",
    "L__self___model_layers_25_self_attn_k_norm_weight",
    "L__self___model_layers_25_self_attn_o_proj.weight",
    "L__self___model_layers_25_self_attn_q_norm_weight",
    "L__self___model_layers_26_input_layernorm_weight",
    "L__self___model_layers_26_mlp_down_proj.weight",
    "L__self___model_layers_26_mlp_gate_proj.weight",
    "L__self___model_layers_26_mlp_up_proj.weight",
    "L__self___model_layers_26_post_attention_layernorm_weight",
    "L__self___model_layers_26_self_attn_k_norm_weight",
    "L__self___model_layers_26_self_attn_o_proj.weight",
    "L__self___model_layers_26_self_attn_q_norm_weight",
    "L__self___model_layers_27_input_layernorm_weight",
    "L__self___model_layers_27_mlp_down_proj.weight",
    "L__self___model_layers_27_mlp_gate_proj.weight",
    "L__self___model_layers_27_mlp_up_proj.weight",
    "L__self___model_layers_27_post_attention_layernorm_weight",
    "L__self___model_layers_27_self_attn_k_norm_weight",
    "L__self___model_layers_27_self_attn_o_proj.weight",
    "L__self___model_layers_27_self_attn_q_norm_weight",
    "L__self___model_layers_28_input_layernorm_weight",
    "L__self___model_layers_28_mlp_down_proj.weight",
    "L__self___model_layers_28_mlp_gate_proj.weight",
    "L__self___model_layers_28_mlp_up_proj.weight",
    "L__self___model_layers_28_post_attention_layernorm_weight",
    "L__self___model_layers_28_self_attn_k_norm_weight",
    "L__self___model_layers_28_self_attn_o_proj.weight",
    "L__self___model_layers_28_self_attn_q_norm_weight",
    "L__self___model_layers_29_input_layernorm_weight",
    "L__self___model_layers_29_mlp_down_proj.weight",
    "L__self___model_layers_29_mlp_gate_proj.weight",
    "L__self___model_layers_29_mlp_up_proj.weight",
    "L__self___model_layers_29_post_attention_layernorm_weight",
    "L__self___model_layers_29_self_attn_k_norm_weight",
    "L__self___model_layers_29_self_attn_o_proj.weight",
    "L__self___model_layers_29_self_attn_q_norm_weight",
    "L__self___model_layers_2_input_layernorm_weight",
    "L__self___model_layers_2_mlp_down_proj.weight",
    "L__self___model_layers_2_mlp_gate_proj.weight",
    "L__self___model_layers_2_mlp_up_proj.weight",
    "L__self___model_layers_2_post_attention_layernorm_weight",
    "L__self___model_layers_2_self_attn_k_norm_weight",
    "L__self___model_layers_2_self_attn_o_proj.weight",
    "L__self___model_layers_2_self_attn_q_norm_weight",
    "L__self___model_layers_30_input_layernorm_weight",
    "L__self___model_layers_30_mlp_down_proj.weight",
    "L__self___model_layers_30_mlp_gate_proj.weight",
    "L__self___model_layers_30_mlp_up_proj.weight",
    "L__self___model_layers_30_post_attention_layernorm_weight",
    "L__self___model_layers_30_self_attn_k_norm_weight",
    "L__self___model_layers_30_self_attn_o_proj.weight",
    "L__self___model_layers_30_self_attn_q_norm_weight",
    "L__self___model_layers_31_input_layernorm_weight",
    "L__self___model_layers_31_mlp_down_proj.weight",
    "L__self___model_layers_31_mlp_gate_proj.weight",
    "L__self___model_layers_31_mlp_up_proj.weight",
    "L__self___model_layers_31_post_attention_layernorm_weight",
    "L__self___model_layers_31_self_attn_k_norm_weight",
    "L__self___model_layers_31_self_attn_o_proj.weight",
    "L__self___model_layers_31_self_attn_q_norm_weight",
    "L__self___model_layers_32_input_layernorm_weight",
    "L__self___model_layers_32_mlp_down_proj.weight",
    "L__self___model_layers_32_mlp_gate_proj.weight",
    "L__self___model_layers_32_mlp_up_proj.weight",
    "L__self___model_layers_32_post_attention_layernorm_weight",
    "L__self___model_layers_32_self_attn_k_norm_weight",
    "L__self___model_layers_32_self_attn_o_proj.weight",
    "L__self___model_layers_32_self_attn_q_norm_weight",
    "L__self___model_layers_33_input_layernorm_weight",
    "L__self___model_layers_33_mlp_down_proj.weight",
    "L__self___model_layers_33_mlp_gate_proj.weight",
    "L__self___model_layers_33_mlp_up_proj.weight",
    "L__self___model_layers_33_post_attention_layernorm_weight",
    "L__self___model_layers_33_self_attn_k_norm_weight",
    "L__self___model_layers_33_self_attn_o_proj.weight",
    "L__self___model_layers_33_self_attn_q_norm_weight",
    "L__self___model_layers_34_input_layernorm_weight",
    "L__self___model_layers_34_mlp_down_proj.weight",
    "L__self___model_layers_34_mlp_gate_proj.weight",
    "L__self___model_layers_34_mlp_up_proj.weight",
    "L__self___model_layers_34_post_attention_layernorm_weight",
    "L__self___model_layers_34_self_attn_k_norm_weight",
    "L__self___model_layers_34_self_attn_o_proj.weight",
    "L__self___model_layers_34_self_attn_q_norm_weight",
    "L__self___model_layers_35_input_layernorm_weight",
    "L__self___model_layers_35_mlp_down_proj.weight",
    "L__self___model_layers_35_mlp_gate_proj.weight",
    "L__self___model_layers_35_mlp_up_proj.weight",
    "L__self___model_layers_35_post_attention_layernorm_weight",
    "L__self___model_layers_35_self_attn_k_norm_weight",
    "L__self___model_layers_35_self_attn_o_proj.weight",
    "L__self___model_layers_35_self_attn_q_norm_weight",
    "L__self___model_layers_3_input_layernorm_weight",
    "L__self___model_layers_3_mlp_down_proj.weight",
    "L__self___model_layers_3_mlp_gate_proj.weight",
    "L__self___model_layers_3_mlp_up_proj.weight",
    "L__self___model_layers_3_post_attention_layernorm_weight",
    "L__self___model_layers_3_self_attn_k_norm_weight",
    "L__self___model_layers_3_self_attn_o_proj.weight",
    "L__self___model_layers_3_self_attn_q_norm_weight",
    "L__self___model_layers_4_input_layernorm_weight",
    "L__self___model_layers_4_mlp_down_proj.weight",
    "L__self___model_layers_4_mlp_gate_proj.weight",
    "L__self___model_layers_4_mlp_up_proj.weight",
    "L__self___model_layers_4_post_attention_layernorm_weight",
    "L__self___model_layers_4_self_attn_k_norm_weight",
    "L__self___model_layers_4_self_attn_o_proj.weight",
    "L__self___model_layers_4_self_attn_q_norm_weight",
    "L__self___model_layers_5_input_layernorm_weight",
    "L__self___model_layers_5_mlp_down_proj.weight",
    "L__self___model_layers_5_mlp_gate_proj.weight",
    "L__self___model_layers_5_mlp_up_proj.weight",
    "L__self___model_layers_5_post_attention_layernorm_weight",
    "L__self___model_layers_5_self_attn_k_norm_weight",
    "L__self___model_layers_5_self_attn_o_proj.weight",
    "L__self___model_layers_5_self_attn_q_norm_weight",
    "L__self___model_layers_6_input_layernorm_weight",
    "L__self___model_layers_6_mlp_down_proj.weight",
    "L__self___model_layers_6_mlp_gate_proj.weight",
    "L__self___model_layers_6_mlp_up_proj.weight",
    "L__self___model_layers_6_post_attention_layernorm_weight",
    "L__self___model_layers_6_self_attn_k_norm_weight",
    "L__self___model_layers_6_self_attn_o_proj.weight",
    "L__self___model_layers_6_self_attn_q_norm_weight",
    "L__self___model_layers_7_input_layernorm_weight",
    "L__self___model_layers_7_mlp_down_proj.weight",
    "L__self___model_layers_7_mlp_gate_proj.weight",
    "L__self___model_layers_7_mlp_up_proj.weight",
    "L__self___model_layers_7_post_attention_layernorm_weight",
    "L__self___model_layers_7_self_attn_k_norm_weight",
    "L__self___model_layers_7_self_attn_o_proj.weight",
    "L__self___model_layers_7_self_attn_q_norm_weight",
    "L__self___model_layers_8_input_layernorm_weight",
    "L__self___model_layers_8_mlp_down_proj.weight",
    "L__self___model_layers_8_mlp_gate_proj.weight",
    "L__self___model_layers_8_mlp_up_proj.weight",
    "L__self___model_layers_8_post_attention_layernorm_weight",
    "L__self___model_layers_8_self_attn_k_norm_weight",
    "L__self___model_layers_8_self_attn_o_proj.weight",
    "L__self___model_layers_8_self_attn_q_norm_weight",
    "L__self___model_layers_9_input_layernorm_weight",
    "L__self___model_layers_9_mlp_down_proj.weight",
    "L__self___model_layers_9_mlp_gate_proj.weight",
    "L__self___model_layers_9_mlp_up_proj.weight",
    "L__self___model_layers_9_post_attention_layernorm_weight",
    "L__self___model_layers_9_self_attn_k_norm_weight",
    "L__self___model_layers_9_self_attn_o_proj.weight",
    "L__self___model_layers_9_self_attn_q_norm_weight",
    "L__self___model_norm_weight",
}


ROW_MAJOR_FLOAT32_WEIGHTS = {
    "L__self___model_rotary_emb_inv_freq",
}


ALL_WEIGHTS = ROW_MAJOR_BFLOAT16_WEIGHTS | TILE_BFLOAT16_WEIGHTS | ROW_MAJOR_FLOAT32_WEIGHTS


def _state_dict_key(weight_name):
    name = weight_name[len("L__self___"):]
    if name.endswith("_weight"):
        name = name[: -len("_weight")] + ".weight"
    name = name.replace("model_layers_", "model.layers.")
    name = name.replace("model_embed_tokens", "model.embed_tokens")
    name = name.replace("model_norm", "model.norm")
    name = name.replace("model_rotary_emb_inv_freq", "model.rotary_emb.inv_freq")
    name = name.replace("_self_attn_", ".self_attn.")
    name = name.replace("_mlp_", ".mlp.")
    name = name.replace("_input_layernorm", ".input_layernorm")
    name = name.replace("_post_attention_layernorm", ".post_attention_layernorm")
    return name


def load_weights_for__main_from_state_dict():
    device = utils.DeviceGetter.get_device((1, 1))

    model = model_pt.load_pytorch_model()
    state_dict = dict(model.state_dict())
    for name, buf in model.named_buffers():
        if name not in state_dict:
            state_dict[name] = buf

    weights = {}
    for key in ALL_WEIGHTS:
        pt_tensor = state_dict[_state_dict_key(key)]
        ttnn_tensor = ttnn.from_torch(pt_tensor)

        if key in ROW_MAJOR_BFLOAT16_WEIGHTS:
            ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.ROW_MAJOR)
            ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.BFLOAT16)

        if key in TILE_BFLOAT16_WEIGHTS:
            ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.TILE)
            ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.BFLOAT16)
            ttnn_tensor = ttnn.to_device(ttnn_tensor, device, ttnn.DRAM_MEMORY_CONFIG)

        if key in ROW_MAJOR_FLOAT32_WEIGHTS:
            ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.ROW_MAJOR)
            ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.FLOAT32)

        weights[key] = ttnn_tensor

    return weights
