# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
import ttnn
import utils
import model_pt


WEIGHT_FILE_MAP = {
    "transformer.proj_out.bias": "./tensors/arg0.tensorbin",
    "transformer.proj_out.weight": "./tensors/arg1.tensorbin",
    "transformer.norm_out.linear.bias": "./tensors/arg2.tensorbin",
    "transformer.norm_out.linear.weight": "./tensors/arg3.tensorbin",
    "transformer.time_embed.timestep_embedder.linear_2.bias": "./tensors/arg4.tensorbin",
    "transformer.time_embed.timestep_embedder.linear_2.weight": "./tensors/arg5.tensorbin",
    "transformer.time_embed.timestep_embedder.linear_1.bias": "./tensors/arg6.tensorbin",
    "transformer.time_embed.timestep_embedder.linear_1.weight": "./tensors/arg7.tensorbin",
    "transformer.single_transformer_blocks.37.proj_out.bias": "./tensors/arg9.tensorbin",
    "transformer.single_transformer_blocks.37.proj_out.weight": "./tensors/arg10.tensorbin",
    "transformer.single_transformer_blocks.37.proj_mlp.bias": "./tensors/arg11.tensorbin",
    "transformer.single_transformer_blocks.37.proj_mlp.weight": "./tensors/arg12.tensorbin",
    "transformer.single_transformer_blocks.37.norm.linear.bias": "./tensors/arg13.tensorbin",
    "transformer.single_transformer_blocks.37.norm.linear.weight": "./tensors/arg14.tensorbin",
    "transformer.single_transformer_blocks.36.proj_out.bias": "./tensors/arg15.tensorbin",
    "transformer.single_transformer_blocks.36.proj_out.weight": "./tensors/arg16.tensorbin",
    "transformer.single_transformer_blocks.36.proj_mlp.bias": "./tensors/arg17.tensorbin",
    "transformer.single_transformer_blocks.36.proj_mlp.weight": "./tensors/arg18.tensorbin",
    "transformer.single_transformer_blocks.36.norm.linear.bias": "./tensors/arg19.tensorbin",
    "transformer.single_transformer_blocks.36.norm.linear.weight": "./tensors/arg20.tensorbin",
    "transformer.single_transformer_blocks.35.proj_out.bias": "./tensors/arg21.tensorbin",
    "transformer.single_transformer_blocks.35.proj_out.weight": "./tensors/arg22.tensorbin",
    "transformer.single_transformer_blocks.35.proj_mlp.bias": "./tensors/arg23.tensorbin",
    "transformer.single_transformer_blocks.35.proj_mlp.weight": "./tensors/arg24.tensorbin",
    "transformer.single_transformer_blocks.35.norm.linear.bias": "./tensors/arg25.tensorbin",
    "transformer.single_transformer_blocks.35.norm.linear.weight": "./tensors/arg26.tensorbin",
    "transformer.single_transformer_blocks.34.proj_out.bias": "./tensors/arg27.tensorbin",
    "transformer.single_transformer_blocks.34.proj_out.weight": "./tensors/arg28.tensorbin",
    "transformer.single_transformer_blocks.34.proj_mlp.bias": "./tensors/arg29.tensorbin",
    "transformer.single_transformer_blocks.34.proj_mlp.weight": "./tensors/arg30.tensorbin",
    "transformer.single_transformer_blocks.34.norm.linear.bias": "./tensors/arg31.tensorbin",
    "transformer.single_transformer_blocks.34.norm.linear.weight": "./tensors/arg32.tensorbin",
    "transformer.single_transformer_blocks.33.proj_out.bias": "./tensors/arg33.tensorbin",
    "transformer.single_transformer_blocks.33.proj_out.weight": "./tensors/arg34.tensorbin",
    "transformer.single_transformer_blocks.33.proj_mlp.bias": "./tensors/arg35.tensorbin",
    "transformer.single_transformer_blocks.33.proj_mlp.weight": "./tensors/arg36.tensorbin",
    "transformer.single_transformer_blocks.33.norm.linear.bias": "./tensors/arg37.tensorbin",
    "transformer.single_transformer_blocks.33.norm.linear.weight": "./tensors/arg38.tensorbin",
    "transformer.single_transformer_blocks.32.proj_out.bias": "./tensors/arg39.tensorbin",
    "transformer.single_transformer_blocks.32.proj_out.weight": "./tensors/arg40.tensorbin",
    "transformer.single_transformer_blocks.32.proj_mlp.bias": "./tensors/arg41.tensorbin",
    "transformer.single_transformer_blocks.32.proj_mlp.weight": "./tensors/arg42.tensorbin",
    "transformer.single_transformer_blocks.32.norm.linear.bias": "./tensors/arg43.tensorbin",
    "transformer.single_transformer_blocks.32.norm.linear.weight": "./tensors/arg44.tensorbin",
    "transformer.single_transformer_blocks.31.proj_out.bias": "./tensors/arg45.tensorbin",
    "transformer.single_transformer_blocks.31.proj_out.weight": "./tensors/arg46.tensorbin",
    "transformer.single_transformer_blocks.31.proj_mlp.bias": "./tensors/arg47.tensorbin",
    "transformer.single_transformer_blocks.31.proj_mlp.weight": "./tensors/arg48.tensorbin",
    "transformer.single_transformer_blocks.31.norm.linear.bias": "./tensors/arg49.tensorbin",
    "transformer.single_transformer_blocks.31.norm.linear.weight": "./tensors/arg50.tensorbin",
    "transformer.single_transformer_blocks.30.proj_out.bias": "./tensors/arg51.tensorbin",
    "transformer.single_transformer_blocks.30.proj_out.weight": "./tensors/arg52.tensorbin",
    "transformer.single_transformer_blocks.30.proj_mlp.bias": "./tensors/arg53.tensorbin",
    "transformer.single_transformer_blocks.30.proj_mlp.weight": "./tensors/arg54.tensorbin",
    "transformer.single_transformer_blocks.30.norm.linear.bias": "./tensors/arg55.tensorbin",
    "transformer.single_transformer_blocks.30.norm.linear.weight": "./tensors/arg56.tensorbin",
    "transformer.single_transformer_blocks.29.proj_out.bias": "./tensors/arg57.tensorbin",
    "transformer.single_transformer_blocks.29.proj_out.weight": "./tensors/arg58.tensorbin",
    "transformer.single_transformer_blocks.29.proj_mlp.bias": "./tensors/arg59.tensorbin",
    "transformer.single_transformer_blocks.29.proj_mlp.weight": "./tensors/arg60.tensorbin",
    "transformer.single_transformer_blocks.29.norm.linear.bias": "./tensors/arg61.tensorbin",
    "transformer.single_transformer_blocks.29.norm.linear.weight": "./tensors/arg62.tensorbin",
    "transformer.single_transformer_blocks.28.proj_out.bias": "./tensors/arg63.tensorbin",
    "transformer.single_transformer_blocks.28.proj_out.weight": "./tensors/arg64.tensorbin",
    "transformer.single_transformer_blocks.28.proj_mlp.bias": "./tensors/arg65.tensorbin",
    "transformer.single_transformer_blocks.28.proj_mlp.weight": "./tensors/arg66.tensorbin",
    "transformer.single_transformer_blocks.28.norm.linear.bias": "./tensors/arg67.tensorbin",
    "transformer.single_transformer_blocks.28.norm.linear.weight": "./tensors/arg68.tensorbin",
    "transformer.single_transformer_blocks.27.proj_out.bias": "./tensors/arg69.tensorbin",
    "transformer.single_transformer_blocks.27.proj_out.weight": "./tensors/arg70.tensorbin",
    "transformer.single_transformer_blocks.27.proj_mlp.bias": "./tensors/arg71.tensorbin",
    "transformer.single_transformer_blocks.27.proj_mlp.weight": "./tensors/arg72.tensorbin",
    "transformer.single_transformer_blocks.27.norm.linear.bias": "./tensors/arg73.tensorbin",
    "transformer.single_transformer_blocks.27.norm.linear.weight": "./tensors/arg74.tensorbin",
    "transformer.single_transformer_blocks.26.proj_out.bias": "./tensors/arg75.tensorbin",
    "transformer.single_transformer_blocks.26.proj_out.weight": "./tensors/arg76.tensorbin",
    "transformer.single_transformer_blocks.26.proj_mlp.bias": "./tensors/arg77.tensorbin",
    "transformer.single_transformer_blocks.26.proj_mlp.weight": "./tensors/arg78.tensorbin",
    "transformer.single_transformer_blocks.26.norm.linear.bias": "./tensors/arg79.tensorbin",
    "transformer.single_transformer_blocks.26.norm.linear.weight": "./tensors/arg80.tensorbin",
    "transformer.single_transformer_blocks.25.proj_out.bias": "./tensors/arg81.tensorbin",
    "transformer.single_transformer_blocks.25.proj_out.weight": "./tensors/arg82.tensorbin",
    "transformer.single_transformer_blocks.25.proj_mlp.bias": "./tensors/arg83.tensorbin",
    "transformer.single_transformer_blocks.25.proj_mlp.weight": "./tensors/arg84.tensorbin",
    "transformer.single_transformer_blocks.25.norm.linear.bias": "./tensors/arg85.tensorbin",
    "transformer.single_transformer_blocks.25.norm.linear.weight": "./tensors/arg86.tensorbin",
    "transformer.single_transformer_blocks.24.proj_out.bias": "./tensors/arg87.tensorbin",
    "transformer.single_transformer_blocks.24.proj_out.weight": "./tensors/arg88.tensorbin",
    "transformer.single_transformer_blocks.24.proj_mlp.bias": "./tensors/arg89.tensorbin",
    "transformer.single_transformer_blocks.24.proj_mlp.weight": "./tensors/arg90.tensorbin",
    "transformer.single_transformer_blocks.24.norm.linear.bias": "./tensors/arg91.tensorbin",
    "transformer.single_transformer_blocks.24.norm.linear.weight": "./tensors/arg92.tensorbin",
    "transformer.single_transformer_blocks.23.proj_out.bias": "./tensors/arg93.tensorbin",
    "transformer.single_transformer_blocks.23.proj_out.weight": "./tensors/arg94.tensorbin",
    "transformer.single_transformer_blocks.23.proj_mlp.bias": "./tensors/arg95.tensorbin",
    "transformer.single_transformer_blocks.23.proj_mlp.weight": "./tensors/arg96.tensorbin",
    "transformer.single_transformer_blocks.23.norm.linear.bias": "./tensors/arg97.tensorbin",
    "transformer.single_transformer_blocks.23.norm.linear.weight": "./tensors/arg98.tensorbin",
    "transformer.single_transformer_blocks.22.proj_out.bias": "./tensors/arg99.tensorbin",
    "transformer.single_transformer_blocks.22.proj_out.weight": "./tensors/arg100.tensorbin",
    "transformer.single_transformer_blocks.22.proj_mlp.bias": "./tensors/arg101.tensorbin",
    "transformer.single_transformer_blocks.22.proj_mlp.weight": "./tensors/arg102.tensorbin",
    "transformer.single_transformer_blocks.22.norm.linear.bias": "./tensors/arg103.tensorbin",
    "transformer.single_transformer_blocks.22.norm.linear.weight": "./tensors/arg104.tensorbin",
    "transformer.single_transformer_blocks.21.proj_out.bias": "./tensors/arg105.tensorbin",
    "transformer.single_transformer_blocks.21.proj_out.weight": "./tensors/arg106.tensorbin",
    "transformer.single_transformer_blocks.21.proj_mlp.bias": "./tensors/arg107.tensorbin",
    "transformer.single_transformer_blocks.21.proj_mlp.weight": "./tensors/arg108.tensorbin",
    "transformer.single_transformer_blocks.21.norm.linear.bias": "./tensors/arg109.tensorbin",
    "transformer.single_transformer_blocks.21.norm.linear.weight": "./tensors/arg110.tensorbin",
    "transformer.single_transformer_blocks.20.proj_out.bias": "./tensors/arg111.tensorbin",
    "transformer.single_transformer_blocks.20.proj_out.weight": "./tensors/arg112.tensorbin",
    "transformer.single_transformer_blocks.20.proj_mlp.bias": "./tensors/arg113.tensorbin",
    "transformer.single_transformer_blocks.20.proj_mlp.weight": "./tensors/arg114.tensorbin",
    "transformer.single_transformer_blocks.20.norm.linear.bias": "./tensors/arg115.tensorbin",
    "transformer.single_transformer_blocks.20.norm.linear.weight": "./tensors/arg116.tensorbin",
    "transformer.single_transformer_blocks.19.proj_out.bias": "./tensors/arg117.tensorbin",
    "transformer.single_transformer_blocks.19.proj_out.weight": "./tensors/arg118.tensorbin",
    "transformer.single_transformer_blocks.19.proj_mlp.bias": "./tensors/arg119.tensorbin",
    "transformer.single_transformer_blocks.19.proj_mlp.weight": "./tensors/arg120.tensorbin",
    "transformer.single_transformer_blocks.19.norm.linear.bias": "./tensors/arg121.tensorbin",
    "transformer.single_transformer_blocks.19.norm.linear.weight": "./tensors/arg122.tensorbin",
    "transformer.single_transformer_blocks.18.proj_out.bias": "./tensors/arg123.tensorbin",
    "transformer.single_transformer_blocks.18.proj_out.weight": "./tensors/arg124.tensorbin",
    "transformer.single_transformer_blocks.18.proj_mlp.bias": "./tensors/arg125.tensorbin",
    "transformer.single_transformer_blocks.18.proj_mlp.weight": "./tensors/arg126.tensorbin",
    "transformer.single_transformer_blocks.18.norm.linear.bias": "./tensors/arg127.tensorbin",
    "transformer.single_transformer_blocks.18.norm.linear.weight": "./tensors/arg128.tensorbin",
    "transformer.single_transformer_blocks.17.proj_out.bias": "./tensors/arg129.tensorbin",
    "transformer.single_transformer_blocks.17.proj_out.weight": "./tensors/arg130.tensorbin",
    "transformer.single_transformer_blocks.17.proj_mlp.bias": "./tensors/arg131.tensorbin",
    "transformer.single_transformer_blocks.17.proj_mlp.weight": "./tensors/arg132.tensorbin",
    "transformer.single_transformer_blocks.17.norm.linear.bias": "./tensors/arg133.tensorbin",
    "transformer.single_transformer_blocks.17.norm.linear.weight": "./tensors/arg134.tensorbin",
    "transformer.single_transformer_blocks.16.proj_out.bias": "./tensors/arg135.tensorbin",
    "transformer.single_transformer_blocks.16.proj_out.weight": "./tensors/arg136.tensorbin",
    "transformer.single_transformer_blocks.16.proj_mlp.bias": "./tensors/arg137.tensorbin",
    "transformer.single_transformer_blocks.16.proj_mlp.weight": "./tensors/arg138.tensorbin",
    "transformer.single_transformer_blocks.16.norm.linear.bias": "./tensors/arg139.tensorbin",
    "transformer.single_transformer_blocks.16.norm.linear.weight": "./tensors/arg140.tensorbin",
    "transformer.single_transformer_blocks.15.proj_out.bias": "./tensors/arg141.tensorbin",
    "transformer.single_transformer_blocks.15.proj_out.weight": "./tensors/arg142.tensorbin",
    "transformer.single_transformer_blocks.15.proj_mlp.bias": "./tensors/arg143.tensorbin",
    "transformer.single_transformer_blocks.15.proj_mlp.weight": "./tensors/arg144.tensorbin",
    "transformer.single_transformer_blocks.15.norm.linear.bias": "./tensors/arg145.tensorbin",
    "transformer.single_transformer_blocks.15.norm.linear.weight": "./tensors/arg146.tensorbin",
    "transformer.single_transformer_blocks.14.proj_out.bias": "./tensors/arg147.tensorbin",
    "transformer.single_transformer_blocks.14.proj_out.weight": "./tensors/arg148.tensorbin",
    "transformer.single_transformer_blocks.14.proj_mlp.bias": "./tensors/arg149.tensorbin",
    "transformer.single_transformer_blocks.14.proj_mlp.weight": "./tensors/arg150.tensorbin",
    "transformer.single_transformer_blocks.14.norm.linear.bias": "./tensors/arg151.tensorbin",
    "transformer.single_transformer_blocks.14.norm.linear.weight": "./tensors/arg152.tensorbin",
    "transformer.single_transformer_blocks.13.proj_out.bias": "./tensors/arg153.tensorbin",
    "transformer.single_transformer_blocks.13.proj_out.weight": "./tensors/arg154.tensorbin",
    "transformer.single_transformer_blocks.13.proj_mlp.bias": "./tensors/arg155.tensorbin",
    "transformer.single_transformer_blocks.13.proj_mlp.weight": "./tensors/arg156.tensorbin",
    "transformer.single_transformer_blocks.13.norm.linear.bias": "./tensors/arg157.tensorbin",
    "transformer.single_transformer_blocks.13.norm.linear.weight": "./tensors/arg158.tensorbin",
    "transformer.single_transformer_blocks.12.proj_out.bias": "./tensors/arg159.tensorbin",
    "transformer.single_transformer_blocks.12.proj_out.weight": "./tensors/arg160.tensorbin",
    "transformer.single_transformer_blocks.12.proj_mlp.bias": "./tensors/arg161.tensorbin",
    "transformer.single_transformer_blocks.12.proj_mlp.weight": "./tensors/arg162.tensorbin",
    "transformer.single_transformer_blocks.12.norm.linear.bias": "./tensors/arg163.tensorbin",
    "transformer.single_transformer_blocks.12.norm.linear.weight": "./tensors/arg164.tensorbin",
    "transformer.single_transformer_blocks.11.proj_out.bias": "./tensors/arg165.tensorbin",
    "transformer.single_transformer_blocks.11.proj_out.weight": "./tensors/arg166.tensorbin",
    "transformer.single_transformer_blocks.11.proj_mlp.bias": "./tensors/arg167.tensorbin",
    "transformer.single_transformer_blocks.11.proj_mlp.weight": "./tensors/arg168.tensorbin",
    "transformer.single_transformer_blocks.11.norm.linear.bias": "./tensors/arg169.tensorbin",
    "transformer.single_transformer_blocks.11.norm.linear.weight": "./tensors/arg170.tensorbin",
    "transformer.single_transformer_blocks.10.proj_out.bias": "./tensors/arg171.tensorbin",
    "transformer.single_transformer_blocks.10.proj_out.weight": "./tensors/arg172.tensorbin",
    "transformer.single_transformer_blocks.10.proj_mlp.bias": "./tensors/arg173.tensorbin",
    "transformer.single_transformer_blocks.10.proj_mlp.weight": "./tensors/arg174.tensorbin",
    "transformer.single_transformer_blocks.10.norm.linear.bias": "./tensors/arg175.tensorbin",
    "transformer.single_transformer_blocks.10.norm.linear.weight": "./tensors/arg176.tensorbin",
    "transformer.single_transformer_blocks.9.proj_out.bias": "./tensors/arg177.tensorbin",
    "transformer.single_transformer_blocks.9.proj_out.weight": "./tensors/arg178.tensorbin",
    "transformer.single_transformer_blocks.9.proj_mlp.bias": "./tensors/arg179.tensorbin",
    "transformer.single_transformer_blocks.9.proj_mlp.weight": "./tensors/arg180.tensorbin",
    "transformer.single_transformer_blocks.9.norm.linear.bias": "./tensors/arg181.tensorbin",
    "transformer.single_transformer_blocks.9.norm.linear.weight": "./tensors/arg182.tensorbin",
    "transformer.single_transformer_blocks.8.proj_out.bias": "./tensors/arg183.tensorbin",
    "transformer.single_transformer_blocks.8.proj_out.weight": "./tensors/arg184.tensorbin",
    "transformer.single_transformer_blocks.8.proj_mlp.bias": "./tensors/arg185.tensorbin",
    "transformer.single_transformer_blocks.8.proj_mlp.weight": "./tensors/arg186.tensorbin",
    "transformer.single_transformer_blocks.8.norm.linear.bias": "./tensors/arg187.tensorbin",
    "transformer.single_transformer_blocks.8.norm.linear.weight": "./tensors/arg188.tensorbin",
    "transformer.single_transformer_blocks.7.proj_out.bias": "./tensors/arg189.tensorbin",
    "transformer.single_transformer_blocks.7.proj_out.weight": "./tensors/arg190.tensorbin",
    "transformer.single_transformer_blocks.7.proj_mlp.bias": "./tensors/arg191.tensorbin",
    "transformer.single_transformer_blocks.7.proj_mlp.weight": "./tensors/arg192.tensorbin",
    "transformer.single_transformer_blocks.7.norm.linear.bias": "./tensors/arg193.tensorbin",
    "transformer.single_transformer_blocks.7.norm.linear.weight": "./tensors/arg194.tensorbin",
    "transformer.single_transformer_blocks.6.proj_out.bias": "./tensors/arg195.tensorbin",
    "transformer.single_transformer_blocks.6.proj_out.weight": "./tensors/arg196.tensorbin",
    "transformer.single_transformer_blocks.6.proj_mlp.bias": "./tensors/arg197.tensorbin",
    "transformer.single_transformer_blocks.6.proj_mlp.weight": "./tensors/arg198.tensorbin",
    "transformer.single_transformer_blocks.6.norm.linear.bias": "./tensors/arg199.tensorbin",
    "transformer.single_transformer_blocks.6.norm.linear.weight": "./tensors/arg200.tensorbin",
    "transformer.single_transformer_blocks.5.proj_out.bias": "./tensors/arg201.tensorbin",
    "transformer.single_transformer_blocks.5.proj_out.weight": "./tensors/arg202.tensorbin",
    "transformer.single_transformer_blocks.5.proj_mlp.bias": "./tensors/arg203.tensorbin",
    "transformer.single_transformer_blocks.5.proj_mlp.weight": "./tensors/arg204.tensorbin",
    "transformer.single_transformer_blocks.5.norm.linear.bias": "./tensors/arg205.tensorbin",
    "transformer.single_transformer_blocks.5.norm.linear.weight": "./tensors/arg206.tensorbin",
    "transformer.single_transformer_blocks.4.proj_out.bias": "./tensors/arg207.tensorbin",
    "transformer.single_transformer_blocks.4.proj_out.weight": "./tensors/arg208.tensorbin",
    "transformer.single_transformer_blocks.4.proj_mlp.bias": "./tensors/arg209.tensorbin",
    "transformer.single_transformer_blocks.4.proj_mlp.weight": "./tensors/arg210.tensorbin",
    "transformer.single_transformer_blocks.4.norm.linear.bias": "./tensors/arg211.tensorbin",
    "transformer.single_transformer_blocks.4.norm.linear.weight": "./tensors/arg212.tensorbin",
    "transformer.single_transformer_blocks.3.proj_out.bias": "./tensors/arg213.tensorbin",
    "transformer.single_transformer_blocks.3.proj_out.weight": "./tensors/arg214.tensorbin",
    "transformer.single_transformer_blocks.3.proj_mlp.bias": "./tensors/arg215.tensorbin",
    "transformer.single_transformer_blocks.3.proj_mlp.weight": "./tensors/arg216.tensorbin",
    "transformer.single_transformer_blocks.3.norm.linear.bias": "./tensors/arg217.tensorbin",
    "transformer.single_transformer_blocks.3.norm.linear.weight": "./tensors/arg218.tensorbin",
    "transformer.single_transformer_blocks.2.proj_out.bias": "./tensors/arg219.tensorbin",
    "transformer.single_transformer_blocks.2.proj_out.weight": "./tensors/arg220.tensorbin",
    "transformer.single_transformer_blocks.2.proj_mlp.bias": "./tensors/arg221.tensorbin",
    "transformer.single_transformer_blocks.2.proj_mlp.weight": "./tensors/arg222.tensorbin",
    "transformer.single_transformer_blocks.2.norm.linear.bias": "./tensors/arg223.tensorbin",
    "transformer.single_transformer_blocks.2.norm.linear.weight": "./tensors/arg224.tensorbin",
    "transformer.single_transformer_blocks.1.proj_out.bias": "./tensors/arg225.tensorbin",
    "transformer.single_transformer_blocks.1.proj_out.weight": "./tensors/arg226.tensorbin",
    "transformer.single_transformer_blocks.1.proj_mlp.bias": "./tensors/arg227.tensorbin",
    "transformer.single_transformer_blocks.1.proj_mlp.weight": "./tensors/arg228.tensorbin",
    "transformer.single_transformer_blocks.1.norm.linear.bias": "./tensors/arg229.tensorbin",
    "transformer.single_transformer_blocks.1.norm.linear.weight": "./tensors/arg230.tensorbin",
    "transformer.single_transformer_blocks.0.proj_out.bias": "./tensors/arg231.tensorbin",
    "transformer.single_transformer_blocks.0.proj_out.weight": "./tensors/arg232.tensorbin",
    "transformer.single_transformer_blocks.0.proj_mlp.bias": "./tensors/arg233.tensorbin",
    "transformer.single_transformer_blocks.0.proj_mlp.weight": "./tensors/arg234.tensorbin",
    "transformer.single_transformer_blocks.0.norm.linear.bias": "./tensors/arg235.tensorbin",
    "transformer.single_transformer_blocks.0.norm.linear.weight": "./tensors/arg236.tensorbin",
    "transformer.transformer_blocks.7.ff.net.2.bias": "./tensors/arg237.tensorbin",
    "transformer.transformer_blocks.7.ff.net.2.weight": "./tensors/arg238.tensorbin",
    "transformer.transformer_blocks.7.ff.net.0.proj.bias": "./tensors/arg239.tensorbin",
    "transformer.transformer_blocks.7.ff.net.0.proj.weight": "./tensors/arg240.tensorbin",
    "transformer.transformer_blocks.7.norm1.linear.bias": "./tensors/arg241.tensorbin",
    "transformer.transformer_blocks.7.norm1.linear.weight": "./tensors/arg242.tensorbin",
    "transformer.transformer_blocks.7.attn.to_out.0.bias": "./tensors/arg243.tensorbin",
    "transformer.transformer_blocks.7.attn.to_out.0.weight": "./tensors/arg244.tensorbin",
    "transformer.transformer_blocks.7.attn.to_v.bias": "./tensors/arg245.tensorbin",
    "transformer.transformer_blocks.7.attn.to_v.weight": "./tensors/arg246.tensorbin",
    "transformer.transformer_blocks.6.ff.net.2.bias": "./tensors/arg247.tensorbin",
    "transformer.transformer_blocks.6.ff.net.2.weight": "./tensors/arg248.tensorbin",
    "transformer.transformer_blocks.6.ff.net.0.proj.bias": "./tensors/arg249.tensorbin",
    "transformer.transformer_blocks.6.ff.net.0.proj.weight": "./tensors/arg250.tensorbin",
    "transformer.transformer_blocks.6.norm1.linear.bias": "./tensors/arg251.tensorbin",
    "transformer.transformer_blocks.6.norm1.linear.weight": "./tensors/arg252.tensorbin",
    "transformer.transformer_blocks.6.attn.to_out.0.bias": "./tensors/arg253.tensorbin",
    "transformer.transformer_blocks.6.attn.to_out.0.weight": "./tensors/arg254.tensorbin",
    "transformer.transformer_blocks.6.attn.to_v.bias": "./tensors/arg255.tensorbin",
    "transformer.transformer_blocks.6.attn.to_v.weight": "./tensors/arg256.tensorbin",
    "transformer.transformer_blocks.5.ff.net.2.bias": "./tensors/arg257.tensorbin",
    "transformer.transformer_blocks.5.ff.net.2.weight": "./tensors/arg258.tensorbin",
    "transformer.transformer_blocks.5.ff.net.0.proj.bias": "./tensors/arg259.tensorbin",
    "transformer.transformer_blocks.5.ff.net.0.proj.weight": "./tensors/arg260.tensorbin",
    "transformer.transformer_blocks.5.norm1.linear.bias": "./tensors/arg261.tensorbin",
    "transformer.transformer_blocks.5.norm1.linear.weight": "./tensors/arg262.tensorbin",
    "transformer.transformer_blocks.5.attn.to_out.0.bias": "./tensors/arg263.tensorbin",
    "transformer.transformer_blocks.5.attn.to_out.0.weight": "./tensors/arg264.tensorbin",
    "transformer.transformer_blocks.5.attn.to_v.bias": "./tensors/arg265.tensorbin",
    "transformer.transformer_blocks.5.attn.to_v.weight": "./tensors/arg266.tensorbin",
    "transformer.transformer_blocks.4.ff.net.2.bias": "./tensors/arg267.tensorbin",
    "transformer.transformer_blocks.4.ff.net.2.weight": "./tensors/arg268.tensorbin",
    "transformer.transformer_blocks.4.ff.net.0.proj.bias": "./tensors/arg269.tensorbin",
    "transformer.transformer_blocks.4.ff.net.0.proj.weight": "./tensors/arg270.tensorbin",
    "transformer.transformer_blocks.4.norm1.linear.bias": "./tensors/arg271.tensorbin",
    "transformer.transformer_blocks.4.norm1.linear.weight": "./tensors/arg272.tensorbin",
    "transformer.transformer_blocks.4.attn.to_out.0.bias": "./tensors/arg273.tensorbin",
    "transformer.transformer_blocks.4.attn.to_out.0.weight": "./tensors/arg274.tensorbin",
    "transformer.transformer_blocks.4.attn.to_v.bias": "./tensors/arg275.tensorbin",
    "transformer.transformer_blocks.4.attn.to_v.weight": "./tensors/arg276.tensorbin",
    "transformer.transformer_blocks.3.ff.net.2.bias": "./tensors/arg277.tensorbin",
    "transformer.transformer_blocks.3.ff.net.2.weight": "./tensors/arg278.tensorbin",
    "transformer.transformer_blocks.3.ff.net.0.proj.bias": "./tensors/arg279.tensorbin",
    "transformer.transformer_blocks.3.ff.net.0.proj.weight": "./tensors/arg280.tensorbin",
    "transformer.transformer_blocks.3.norm1.linear.bias": "./tensors/arg281.tensorbin",
    "transformer.transformer_blocks.3.norm1.linear.weight": "./tensors/arg282.tensorbin",
    "transformer.transformer_blocks.3.attn.to_out.0.bias": "./tensors/arg283.tensorbin",
    "transformer.transformer_blocks.3.attn.to_out.0.weight": "./tensors/arg284.tensorbin",
    "transformer.transformer_blocks.3.attn.to_v.bias": "./tensors/arg285.tensorbin",
    "transformer.transformer_blocks.3.attn.to_v.weight": "./tensors/arg286.tensorbin",
    "transformer.transformer_blocks.2.ff.net.2.bias": "./tensors/arg287.tensorbin",
    "transformer.transformer_blocks.2.ff.net.2.weight": "./tensors/arg288.tensorbin",
    "transformer.transformer_blocks.2.ff.net.0.proj.bias": "./tensors/arg289.tensorbin",
    "transformer.transformer_blocks.2.ff.net.0.proj.weight": "./tensors/arg290.tensorbin",
    "transformer.transformer_blocks.2.norm1.linear.bias": "./tensors/arg291.tensorbin",
    "transformer.transformer_blocks.2.norm1.linear.weight": "./tensors/arg292.tensorbin",
    "transformer.transformer_blocks.2.attn.to_out.0.bias": "./tensors/arg293.tensorbin",
    "transformer.transformer_blocks.2.attn.to_out.0.weight": "./tensors/arg294.tensorbin",
    "transformer.transformer_blocks.2.attn.to_v.bias": "./tensors/arg295.tensorbin",
    "transformer.transformer_blocks.2.attn.to_v.weight": "./tensors/arg296.tensorbin",
    "transformer.transformer_blocks.1.ff.net.2.bias": "./tensors/arg297.tensorbin",
    "transformer.transformer_blocks.1.ff.net.2.weight": "./tensors/arg298.tensorbin",
    "transformer.transformer_blocks.1.ff.net.0.proj.bias": "./tensors/arg299.tensorbin",
    "transformer.transformer_blocks.1.ff.net.0.proj.weight": "./tensors/arg300.tensorbin",
    "transformer.transformer_blocks.1.norm1.linear.bias": "./tensors/arg301.tensorbin",
    "transformer.transformer_blocks.1.norm1.linear.weight": "./tensors/arg302.tensorbin",
    "transformer.transformer_blocks.1.attn.to_out.0.bias": "./tensors/arg303.tensorbin",
    "transformer.transformer_blocks.1.attn.to_out.0.weight": "./tensors/arg304.tensorbin",
    "transformer.transformer_blocks.1.attn.to_v.bias": "./tensors/arg305.tensorbin",
    "transformer.transformer_blocks.1.attn.to_v.weight": "./tensors/arg306.tensorbin",
    "transformer.transformer_blocks.0.ff.net.2.bias": "./tensors/arg307.tensorbin",
    "transformer.transformer_blocks.0.ff.net.2.weight": "./tensors/arg308.tensorbin",
    "transformer.transformer_blocks.0.ff.net.0.proj.bias": "./tensors/arg309.tensorbin",
    "transformer.transformer_blocks.0.ff.net.0.proj.weight": "./tensors/arg310.tensorbin",
    "transformer.transformer_blocks.0.norm1.linear.bias": "./tensors/arg311.tensorbin",
    "transformer.transformer_blocks.0.norm1.linear.weight": "./tensors/arg312.tensorbin",
    "transformer.transformer_blocks.0.attn.to_out.0.bias": "./tensors/arg313.tensorbin",
    "transformer.transformer_blocks.0.attn.to_out.0.weight": "./tensors/arg314.tensorbin",
    "transformer.transformer_blocks.0.attn.to_v.bias": "./tensors/arg315.tensorbin",
    "transformer.transformer_blocks.0.attn.to_v.weight": "./tensors/arg316.tensorbin",
    "transformer.x_embedder.bias": "./tensors/arg317.tensorbin",
    "transformer.x_embedder.weight": "./tensors/arg318.tensorbin",
    "transformer.transformer_blocks.0.attn.add_v_proj.bias": "./tensors/arg320.tensorbin",
    "transformer.transformer_blocks.0.attn.add_v_proj.weight": "./tensors/arg321.tensorbin",
    "transformer.transformer_blocks.0.norm1_context.linear.bias": "./tensors/arg322.tensorbin",
    "transformer.transformer_blocks.0.norm1_context.linear.weight": "./tensors/arg323.tensorbin",
    "transformer.caption_projection.0.linear.weight": "./tensors/arg324.tensorbin",
    "transformer.context_embedder.bias": "./tensors/arg326.tensorbin",
    "transformer.context_embedder.weight": "./tensors/arg327.tensorbin",
    "transformer.transformer_blocks.0.attn.norm_k.weight": "./tensors/arg332.tensorbin",
    "transformer.transformer_blocks.0.attn.to_k.bias": "./tensors/arg333.tensorbin",
    "transformer.transformer_blocks.0.attn.to_k.weight": "./tensors/arg334.tensorbin",
    "transformer.transformer_blocks.0.attn.norm_added_k.weight": "./tensors/arg335.tensorbin",
    "transformer.transformer_blocks.0.attn.add_k_proj.bias": "./tensors/arg336.tensorbin",
    "transformer.transformer_blocks.0.attn.add_k_proj.weight": "./tensors/arg337.tensorbin",
    "transformer.transformer_blocks.0.attn.norm_q.weight": "./tensors/arg338.tensorbin",
    "transformer.transformer_blocks.0.attn.to_q.bias": "./tensors/arg339.tensorbin",
    "transformer.transformer_blocks.0.attn.to_q.weight": "./tensors/arg340.tensorbin",
    "transformer.transformer_blocks.0.attn.norm_added_q.weight": "./tensors/arg341.tensorbin",
    "transformer.transformer_blocks.0.attn.add_q_proj.bias": "./tensors/arg342.tensorbin",
    "transformer.transformer_blocks.0.attn.add_q_proj.weight": "./tensors/arg343.tensorbin",
    "transformer.transformer_blocks.1.attn.add_v_proj.bias": "./tensors/arg344.tensorbin",
    "transformer.transformer_blocks.1.attn.add_v_proj.weight": "./tensors/arg345.tensorbin",
    "transformer.transformer_blocks.1.norm1_context.linear.bias": "./tensors/arg346.tensorbin",
    "transformer.transformer_blocks.1.norm1_context.linear.weight": "./tensors/arg347.tensorbin",
    "transformer.caption_projection.1.linear.weight": "./tensors/arg348.tensorbin",
    "transformer.transformer_blocks.0.ff_context.net.2.bias": "./tensors/arg350.tensorbin",
    "transformer.transformer_blocks.0.ff_context.net.2.weight": "./tensors/arg351.tensorbin",
    "transformer.transformer_blocks.0.ff_context.net.0.proj.bias": "./tensors/arg352.tensorbin",
    "transformer.transformer_blocks.0.ff_context.net.0.proj.weight": "./tensors/arg353.tensorbin",
    "transformer.transformer_blocks.0.attn.to_add_out.bias": "./tensors/arg354.tensorbin",
    "transformer.transformer_blocks.0.attn.to_add_out.weight": "./tensors/arg355.tensorbin",
    "transformer.transformer_blocks.1.attn.norm_k.weight": "./tensors/arg356.tensorbin",
    "transformer.transformer_blocks.1.attn.to_k.bias": "./tensors/arg357.tensorbin",
    "transformer.transformer_blocks.1.attn.to_k.weight": "./tensors/arg358.tensorbin",
    "transformer.transformer_blocks.1.attn.norm_added_k.weight": "./tensors/arg359.tensorbin",
    "transformer.transformer_blocks.1.attn.add_k_proj.bias": "./tensors/arg360.tensorbin",
    "transformer.transformer_blocks.1.attn.add_k_proj.weight": "./tensors/arg361.tensorbin",
    "transformer.transformer_blocks.1.attn.norm_q.weight": "./tensors/arg362.tensorbin",
    "transformer.transformer_blocks.1.attn.to_q.bias": "./tensors/arg363.tensorbin",
    "transformer.transformer_blocks.1.attn.to_q.weight": "./tensors/arg364.tensorbin",
    "transformer.transformer_blocks.1.attn.norm_added_q.weight": "./tensors/arg365.tensorbin",
    "transformer.transformer_blocks.1.attn.add_q_proj.bias": "./tensors/arg366.tensorbin",
    "transformer.transformer_blocks.1.attn.add_q_proj.weight": "./tensors/arg367.tensorbin",
    "transformer.transformer_blocks.2.attn.add_v_proj.bias": "./tensors/arg368.tensorbin",
    "transformer.transformer_blocks.2.attn.add_v_proj.weight": "./tensors/arg369.tensorbin",
    "transformer.transformer_blocks.2.norm1_context.linear.bias": "./tensors/arg370.tensorbin",
    "transformer.transformer_blocks.2.norm1_context.linear.weight": "./tensors/arg371.tensorbin",
    "transformer.caption_projection.2.linear.weight": "./tensors/arg372.tensorbin",
    "transformer.transformer_blocks.1.ff_context.net.2.bias": "./tensors/arg374.tensorbin",
    "transformer.transformer_blocks.1.ff_context.net.2.weight": "./tensors/arg375.tensorbin",
    "transformer.transformer_blocks.1.ff_context.net.0.proj.bias": "./tensors/arg376.tensorbin",
    "transformer.transformer_blocks.1.ff_context.net.0.proj.weight": "./tensors/arg377.tensorbin",
    "transformer.transformer_blocks.1.attn.to_add_out.bias": "./tensors/arg378.tensorbin",
    "transformer.transformer_blocks.1.attn.to_add_out.weight": "./tensors/arg379.tensorbin",
    "transformer.transformer_blocks.2.attn.norm_k.weight": "./tensors/arg380.tensorbin",
    "transformer.transformer_blocks.2.attn.to_k.bias": "./tensors/arg381.tensorbin",
    "transformer.transformer_blocks.2.attn.to_k.weight": "./tensors/arg382.tensorbin",
    "transformer.transformer_blocks.2.attn.norm_added_k.weight": "./tensors/arg383.tensorbin",
    "transformer.transformer_blocks.2.attn.add_k_proj.bias": "./tensors/arg384.tensorbin",
    "transformer.transformer_blocks.2.attn.add_k_proj.weight": "./tensors/arg385.tensorbin",
    "transformer.transformer_blocks.2.attn.norm_q.weight": "./tensors/arg386.tensorbin",
    "transformer.transformer_blocks.2.attn.to_q.bias": "./tensors/arg387.tensorbin",
    "transformer.transformer_blocks.2.attn.to_q.weight": "./tensors/arg388.tensorbin",
    "transformer.transformer_blocks.2.attn.norm_added_q.weight": "./tensors/arg389.tensorbin",
    "transformer.transformer_blocks.2.attn.add_q_proj.bias": "./tensors/arg390.tensorbin",
    "transformer.transformer_blocks.2.attn.add_q_proj.weight": "./tensors/arg391.tensorbin",
    "transformer.transformer_blocks.3.attn.add_v_proj.bias": "./tensors/arg392.tensorbin",
    "transformer.transformer_blocks.3.attn.add_v_proj.weight": "./tensors/arg393.tensorbin",
    "transformer.transformer_blocks.3.norm1_context.linear.bias": "./tensors/arg394.tensorbin",
    "transformer.transformer_blocks.3.norm1_context.linear.weight": "./tensors/arg395.tensorbin",
    "transformer.caption_projection.3.linear.weight": "./tensors/arg396.tensorbin",
    "transformer.transformer_blocks.2.ff_context.net.2.bias": "./tensors/arg398.tensorbin",
    "transformer.transformer_blocks.2.ff_context.net.2.weight": "./tensors/arg399.tensorbin",
    "transformer.transformer_blocks.2.ff_context.net.0.proj.bias": "./tensors/arg400.tensorbin",
    "transformer.transformer_blocks.2.ff_context.net.0.proj.weight": "./tensors/arg401.tensorbin",
    "transformer.transformer_blocks.2.attn.to_add_out.bias": "./tensors/arg402.tensorbin",
    "transformer.transformer_blocks.2.attn.to_add_out.weight": "./tensors/arg403.tensorbin",
    "transformer.transformer_blocks.3.attn.norm_k.weight": "./tensors/arg404.tensorbin",
    "transformer.transformer_blocks.3.attn.to_k.bias": "./tensors/arg405.tensorbin",
    "transformer.transformer_blocks.3.attn.to_k.weight": "./tensors/arg406.tensorbin",
    "transformer.transformer_blocks.3.attn.norm_added_k.weight": "./tensors/arg407.tensorbin",
    "transformer.transformer_blocks.3.attn.add_k_proj.bias": "./tensors/arg408.tensorbin",
    "transformer.transformer_blocks.3.attn.add_k_proj.weight": "./tensors/arg409.tensorbin",
    "transformer.transformer_blocks.3.attn.norm_q.weight": "./tensors/arg410.tensorbin",
    "transformer.transformer_blocks.3.attn.to_q.bias": "./tensors/arg411.tensorbin",
    "transformer.transformer_blocks.3.attn.to_q.weight": "./tensors/arg412.tensorbin",
    "transformer.transformer_blocks.3.attn.norm_added_q.weight": "./tensors/arg413.tensorbin",
    "transformer.transformer_blocks.3.attn.add_q_proj.bias": "./tensors/arg414.tensorbin",
    "transformer.transformer_blocks.3.attn.add_q_proj.weight": "./tensors/arg415.tensorbin",
    "transformer.transformer_blocks.4.attn.add_v_proj.bias": "./tensors/arg416.tensorbin",
    "transformer.transformer_blocks.4.attn.add_v_proj.weight": "./tensors/arg417.tensorbin",
    "transformer.transformer_blocks.4.norm1_context.linear.bias": "./tensors/arg418.tensorbin",
    "transformer.transformer_blocks.4.norm1_context.linear.weight": "./tensors/arg419.tensorbin",
    "transformer.caption_projection.4.linear.weight": "./tensors/arg420.tensorbin",
    "transformer.transformer_blocks.3.ff_context.net.2.bias": "./tensors/arg422.tensorbin",
    "transformer.transformer_blocks.3.ff_context.net.2.weight": "./tensors/arg423.tensorbin",
    "transformer.transformer_blocks.3.ff_context.net.0.proj.bias": "./tensors/arg424.tensorbin",
    "transformer.transformer_blocks.3.ff_context.net.0.proj.weight": "./tensors/arg425.tensorbin",
    "transformer.transformer_blocks.3.attn.to_add_out.bias": "./tensors/arg426.tensorbin",
    "transformer.transformer_blocks.3.attn.to_add_out.weight": "./tensors/arg427.tensorbin",
    "transformer.transformer_blocks.4.attn.norm_k.weight": "./tensors/arg428.tensorbin",
    "transformer.transformer_blocks.4.attn.to_k.bias": "./tensors/arg429.tensorbin",
    "transformer.transformer_blocks.4.attn.to_k.weight": "./tensors/arg430.tensorbin",
    "transformer.transformer_blocks.4.attn.norm_added_k.weight": "./tensors/arg431.tensorbin",
    "transformer.transformer_blocks.4.attn.add_k_proj.bias": "./tensors/arg432.tensorbin",
    "transformer.transformer_blocks.4.attn.add_k_proj.weight": "./tensors/arg433.tensorbin",
    "transformer.transformer_blocks.4.attn.norm_q.weight": "./tensors/arg434.tensorbin",
    "transformer.transformer_blocks.4.attn.to_q.bias": "./tensors/arg435.tensorbin",
    "transformer.transformer_blocks.4.attn.to_q.weight": "./tensors/arg436.tensorbin",
    "transformer.transformer_blocks.4.attn.norm_added_q.weight": "./tensors/arg437.tensorbin",
    "transformer.transformer_blocks.4.attn.add_q_proj.bias": "./tensors/arg438.tensorbin",
    "transformer.transformer_blocks.4.attn.add_q_proj.weight": "./tensors/arg439.tensorbin",
    "transformer.transformer_blocks.5.attn.add_v_proj.bias": "./tensors/arg440.tensorbin",
    "transformer.transformer_blocks.5.attn.add_v_proj.weight": "./tensors/arg441.tensorbin",
    "transformer.transformer_blocks.5.norm1_context.linear.bias": "./tensors/arg442.tensorbin",
    "transformer.transformer_blocks.5.norm1_context.linear.weight": "./tensors/arg443.tensorbin",
    "transformer.caption_projection.5.linear.weight": "./tensors/arg444.tensorbin",
    "transformer.transformer_blocks.4.ff_context.net.2.bias": "./tensors/arg446.tensorbin",
    "transformer.transformer_blocks.4.ff_context.net.2.weight": "./tensors/arg447.tensorbin",
    "transformer.transformer_blocks.4.ff_context.net.0.proj.bias": "./tensors/arg448.tensorbin",
    "transformer.transformer_blocks.4.ff_context.net.0.proj.weight": "./tensors/arg449.tensorbin",
    "transformer.transformer_blocks.4.attn.to_add_out.bias": "./tensors/arg450.tensorbin",
    "transformer.transformer_blocks.4.attn.to_add_out.weight": "./tensors/arg451.tensorbin",
    "transformer.transformer_blocks.5.attn.norm_k.weight": "./tensors/arg452.tensorbin",
    "transformer.transformer_blocks.5.attn.to_k.bias": "./tensors/arg453.tensorbin",
    "transformer.transformer_blocks.5.attn.to_k.weight": "./tensors/arg454.tensorbin",
    "transformer.transformer_blocks.5.attn.norm_added_k.weight": "./tensors/arg455.tensorbin",
    "transformer.transformer_blocks.5.attn.add_k_proj.bias": "./tensors/arg456.tensorbin",
    "transformer.transformer_blocks.5.attn.add_k_proj.weight": "./tensors/arg457.tensorbin",
    "transformer.transformer_blocks.5.attn.norm_q.weight": "./tensors/arg458.tensorbin",
    "transformer.transformer_blocks.5.attn.to_q.bias": "./tensors/arg459.tensorbin",
    "transformer.transformer_blocks.5.attn.to_q.weight": "./tensors/arg460.tensorbin",
    "transformer.transformer_blocks.5.attn.norm_added_q.weight": "./tensors/arg461.tensorbin",
    "transformer.transformer_blocks.5.attn.add_q_proj.bias": "./tensors/arg462.tensorbin",
    "transformer.transformer_blocks.5.attn.add_q_proj.weight": "./tensors/arg463.tensorbin",
    "transformer.transformer_blocks.6.attn.add_v_proj.bias": "./tensors/arg464.tensorbin",
    "transformer.transformer_blocks.6.attn.add_v_proj.weight": "./tensors/arg465.tensorbin",
    "transformer.transformer_blocks.6.norm1_context.linear.bias": "./tensors/arg466.tensorbin",
    "transformer.transformer_blocks.6.norm1_context.linear.weight": "./tensors/arg467.tensorbin",
    "transformer.caption_projection.6.linear.weight": "./tensors/arg468.tensorbin",
    "transformer.transformer_blocks.5.ff_context.net.2.bias": "./tensors/arg470.tensorbin",
    "transformer.transformer_blocks.5.ff_context.net.2.weight": "./tensors/arg471.tensorbin",
    "transformer.transformer_blocks.5.ff_context.net.0.proj.bias": "./tensors/arg472.tensorbin",
    "transformer.transformer_blocks.5.ff_context.net.0.proj.weight": "./tensors/arg473.tensorbin",
    "transformer.transformer_blocks.5.attn.to_add_out.bias": "./tensors/arg474.tensorbin",
    "transformer.transformer_blocks.5.attn.to_add_out.weight": "./tensors/arg475.tensorbin",
    "transformer.transformer_blocks.6.attn.norm_k.weight": "./tensors/arg476.tensorbin",
    "transformer.transformer_blocks.6.attn.to_k.bias": "./tensors/arg477.tensorbin",
    "transformer.transformer_blocks.6.attn.to_k.weight": "./tensors/arg478.tensorbin",
    "transformer.transformer_blocks.6.attn.norm_added_k.weight": "./tensors/arg479.tensorbin",
    "transformer.transformer_blocks.6.attn.add_k_proj.bias": "./tensors/arg480.tensorbin",
    "transformer.transformer_blocks.6.attn.add_k_proj.weight": "./tensors/arg481.tensorbin",
    "transformer.transformer_blocks.6.attn.norm_q.weight": "./tensors/arg482.tensorbin",
    "transformer.transformer_blocks.6.attn.to_q.bias": "./tensors/arg483.tensorbin",
    "transformer.transformer_blocks.6.attn.to_q.weight": "./tensors/arg484.tensorbin",
    "transformer.transformer_blocks.6.attn.norm_added_q.weight": "./tensors/arg485.tensorbin",
    "transformer.transformer_blocks.6.attn.add_q_proj.bias": "./tensors/arg486.tensorbin",
    "transformer.transformer_blocks.6.attn.add_q_proj.weight": "./tensors/arg487.tensorbin",
    "transformer.transformer_blocks.7.attn.add_v_proj.bias": "./tensors/arg488.tensorbin",
    "transformer.transformer_blocks.7.attn.add_v_proj.weight": "./tensors/arg489.tensorbin",
    "transformer.transformer_blocks.7.norm1_context.linear.bias": "./tensors/arg490.tensorbin",
    "transformer.transformer_blocks.7.norm1_context.linear.weight": "./tensors/arg491.tensorbin",
    "transformer.caption_projection.7.linear.weight": "./tensors/arg492.tensorbin",
    "transformer.transformer_blocks.6.ff_context.net.2.bias": "./tensors/arg494.tensorbin",
    "transformer.transformer_blocks.6.ff_context.net.2.weight": "./tensors/arg495.tensorbin",
    "transformer.transformer_blocks.6.ff_context.net.0.proj.bias": "./tensors/arg496.tensorbin",
    "transformer.transformer_blocks.6.ff_context.net.0.proj.weight": "./tensors/arg497.tensorbin",
    "transformer.transformer_blocks.6.attn.to_add_out.bias": "./tensors/arg498.tensorbin",
    "transformer.transformer_blocks.6.attn.to_add_out.weight": "./tensors/arg499.tensorbin",
    "transformer.transformer_blocks.7.attn.norm_k.weight": "./tensors/arg500.tensorbin",
    "transformer.transformer_blocks.7.attn.to_k.bias": "./tensors/arg501.tensorbin",
    "transformer.transformer_blocks.7.attn.to_k.weight": "./tensors/arg502.tensorbin",
    "transformer.transformer_blocks.7.attn.norm_added_k.weight": "./tensors/arg503.tensorbin",
    "transformer.transformer_blocks.7.attn.add_k_proj.bias": "./tensors/arg504.tensorbin",
    "transformer.transformer_blocks.7.attn.add_k_proj.weight": "./tensors/arg505.tensorbin",
    "transformer.transformer_blocks.7.attn.norm_q.weight": "./tensors/arg506.tensorbin",
    "transformer.transformer_blocks.7.attn.to_q.bias": "./tensors/arg507.tensorbin",
    "transformer.transformer_blocks.7.attn.to_q.weight": "./tensors/arg508.tensorbin",
    "transformer.transformer_blocks.7.attn.norm_added_q.weight": "./tensors/arg509.tensorbin",
    "transformer.transformer_blocks.7.attn.add_q_proj.bias": "./tensors/arg510.tensorbin",
    "transformer.transformer_blocks.7.attn.add_q_proj.weight": "./tensors/arg511.tensorbin",
    "transformer.caption_projection.8.linear.weight": "./tensors/arg512.tensorbin",
    "transformer.transformer_blocks.7.ff_context.net.2.bias": "./tensors/arg514.tensorbin",
    "transformer.transformer_blocks.7.ff_context.net.2.weight": "./tensors/arg515.tensorbin",
    "transformer.transformer_blocks.7.ff_context.net.0.proj.bias": "./tensors/arg516.tensorbin",
    "transformer.transformer_blocks.7.ff_context.net.0.proj.weight": "./tensors/arg517.tensorbin",
    "transformer.transformer_blocks.7.attn.to_add_out.bias": "./tensors/arg518.tensorbin",
    "transformer.transformer_blocks.7.attn.to_add_out.weight": "./tensors/arg519.tensorbin",
    "transformer.single_transformer_blocks.0.attn.to_v.bias": "./tensors/arg520.tensorbin",
    "transformer.single_transformer_blocks.0.attn.to_v.weight": "./tensors/arg521.tensorbin",
    "transformer.single_transformer_blocks.0.attn.norm_k.weight": "./tensors/arg522.tensorbin",
    "transformer.single_transformer_blocks.0.attn.to_k.bias": "./tensors/arg523.tensorbin",
    "transformer.single_transformer_blocks.0.attn.to_k.weight": "./tensors/arg524.tensorbin",
    "transformer.single_transformer_blocks.0.attn.norm_q.weight": "./tensors/arg525.tensorbin",
    "transformer.single_transformer_blocks.0.attn.to_q.bias": "./tensors/arg526.tensorbin",
    "transformer.single_transformer_blocks.0.attn.to_q.weight": "./tensors/arg527.tensorbin",
    "transformer.caption_projection.9.linear.weight": "./tensors/arg528.tensorbin",
    "transformer.single_transformer_blocks.1.attn.to_v.bias": "./tensors/arg530.tensorbin",
    "transformer.single_transformer_blocks.1.attn.to_v.weight": "./tensors/arg531.tensorbin",
    "transformer.single_transformer_blocks.1.attn.norm_k.weight": "./tensors/arg532.tensorbin",
    "transformer.single_transformer_blocks.1.attn.to_k.bias": "./tensors/arg533.tensorbin",
    "transformer.single_transformer_blocks.1.attn.to_k.weight": "./tensors/arg534.tensorbin",
    "transformer.single_transformer_blocks.1.attn.norm_q.weight": "./tensors/arg535.tensorbin",
    "transformer.single_transformer_blocks.1.attn.to_q.bias": "./tensors/arg536.tensorbin",
    "transformer.single_transformer_blocks.1.attn.to_q.weight": "./tensors/arg537.tensorbin",
    "transformer.caption_projection.10.linear.weight": "./tensors/arg538.tensorbin",
    "transformer.single_transformer_blocks.2.attn.to_v.bias": "./tensors/arg540.tensorbin",
    "transformer.single_transformer_blocks.2.attn.to_v.weight": "./tensors/arg541.tensorbin",
    "transformer.single_transformer_blocks.2.attn.norm_k.weight": "./tensors/arg542.tensorbin",
    "transformer.single_transformer_blocks.2.attn.to_k.bias": "./tensors/arg543.tensorbin",
    "transformer.single_transformer_blocks.2.attn.to_k.weight": "./tensors/arg544.tensorbin",
    "transformer.single_transformer_blocks.2.attn.norm_q.weight": "./tensors/arg545.tensorbin",
    "transformer.single_transformer_blocks.2.attn.to_q.bias": "./tensors/arg546.tensorbin",
    "transformer.single_transformer_blocks.2.attn.to_q.weight": "./tensors/arg547.tensorbin",
    "transformer.caption_projection.11.linear.weight": "./tensors/arg548.tensorbin",
    "transformer.single_transformer_blocks.3.attn.to_v.bias": "./tensors/arg550.tensorbin",
    "transformer.single_transformer_blocks.3.attn.to_v.weight": "./tensors/arg551.tensorbin",
    "transformer.single_transformer_blocks.3.attn.norm_k.weight": "./tensors/arg552.tensorbin",
    "transformer.single_transformer_blocks.3.attn.to_k.bias": "./tensors/arg553.tensorbin",
    "transformer.single_transformer_blocks.3.attn.to_k.weight": "./tensors/arg554.tensorbin",
    "transformer.single_transformer_blocks.3.attn.norm_q.weight": "./tensors/arg555.tensorbin",
    "transformer.single_transformer_blocks.3.attn.to_q.bias": "./tensors/arg556.tensorbin",
    "transformer.single_transformer_blocks.3.attn.to_q.weight": "./tensors/arg557.tensorbin",
    "transformer.caption_projection.12.linear.weight": "./tensors/arg558.tensorbin",
    "transformer.single_transformer_blocks.4.attn.to_v.bias": "./tensors/arg560.tensorbin",
    "transformer.single_transformer_blocks.4.attn.to_v.weight": "./tensors/arg561.tensorbin",
    "transformer.single_transformer_blocks.4.attn.norm_k.weight": "./tensors/arg562.tensorbin",
    "transformer.single_transformer_blocks.4.attn.to_k.bias": "./tensors/arg563.tensorbin",
    "transformer.single_transformer_blocks.4.attn.to_k.weight": "./tensors/arg564.tensorbin",
    "transformer.single_transformer_blocks.4.attn.norm_q.weight": "./tensors/arg565.tensorbin",
    "transformer.single_transformer_blocks.4.attn.to_q.bias": "./tensors/arg566.tensorbin",
    "transformer.single_transformer_blocks.4.attn.to_q.weight": "./tensors/arg567.tensorbin",
    "transformer.caption_projection.13.linear.weight": "./tensors/arg568.tensorbin",
    "transformer.single_transformer_blocks.5.attn.to_v.bias": "./tensors/arg570.tensorbin",
    "transformer.single_transformer_blocks.5.attn.to_v.weight": "./tensors/arg571.tensorbin",
    "transformer.single_transformer_blocks.5.attn.norm_k.weight": "./tensors/arg572.tensorbin",
    "transformer.single_transformer_blocks.5.attn.to_k.bias": "./tensors/arg573.tensorbin",
    "transformer.single_transformer_blocks.5.attn.to_k.weight": "./tensors/arg574.tensorbin",
    "transformer.single_transformer_blocks.5.attn.norm_q.weight": "./tensors/arg575.tensorbin",
    "transformer.single_transformer_blocks.5.attn.to_q.bias": "./tensors/arg576.tensorbin",
    "transformer.single_transformer_blocks.5.attn.to_q.weight": "./tensors/arg577.tensorbin",
    "transformer.caption_projection.14.linear.weight": "./tensors/arg578.tensorbin",
    "transformer.single_transformer_blocks.6.attn.to_v.bias": "./tensors/arg580.tensorbin",
    "transformer.single_transformer_blocks.6.attn.to_v.weight": "./tensors/arg581.tensorbin",
    "transformer.single_transformer_blocks.6.attn.norm_k.weight": "./tensors/arg582.tensorbin",
    "transformer.single_transformer_blocks.6.attn.to_k.bias": "./tensors/arg583.tensorbin",
    "transformer.single_transformer_blocks.6.attn.to_k.weight": "./tensors/arg584.tensorbin",
    "transformer.single_transformer_blocks.6.attn.norm_q.weight": "./tensors/arg585.tensorbin",
    "transformer.single_transformer_blocks.6.attn.to_q.bias": "./tensors/arg586.tensorbin",
    "transformer.single_transformer_blocks.6.attn.to_q.weight": "./tensors/arg587.tensorbin",
    "transformer.caption_projection.15.linear.weight": "./tensors/arg588.tensorbin",
    "transformer.single_transformer_blocks.7.attn.to_v.bias": "./tensors/arg590.tensorbin",
    "transformer.single_transformer_blocks.7.attn.to_v.weight": "./tensors/arg591.tensorbin",
    "transformer.single_transformer_blocks.7.attn.norm_k.weight": "./tensors/arg592.tensorbin",
    "transformer.single_transformer_blocks.7.attn.to_k.bias": "./tensors/arg593.tensorbin",
    "transformer.single_transformer_blocks.7.attn.to_k.weight": "./tensors/arg594.tensorbin",
    "transformer.single_transformer_blocks.7.attn.norm_q.weight": "./tensors/arg595.tensorbin",
    "transformer.single_transformer_blocks.7.attn.to_q.bias": "./tensors/arg596.tensorbin",
    "transformer.single_transformer_blocks.7.attn.to_q.weight": "./tensors/arg597.tensorbin",
    "transformer.caption_projection.16.linear.weight": "./tensors/arg598.tensorbin",
    "transformer.single_transformer_blocks.8.attn.to_v.bias": "./tensors/arg600.tensorbin",
    "transformer.single_transformer_blocks.8.attn.to_v.weight": "./tensors/arg601.tensorbin",
    "transformer.single_transformer_blocks.8.attn.norm_k.weight": "./tensors/arg602.tensorbin",
    "transformer.single_transformer_blocks.8.attn.to_k.bias": "./tensors/arg603.tensorbin",
    "transformer.single_transformer_blocks.8.attn.to_k.weight": "./tensors/arg604.tensorbin",
    "transformer.single_transformer_blocks.8.attn.norm_q.weight": "./tensors/arg605.tensorbin",
    "transformer.single_transformer_blocks.8.attn.to_q.bias": "./tensors/arg606.tensorbin",
    "transformer.single_transformer_blocks.8.attn.to_q.weight": "./tensors/arg607.tensorbin",
    "transformer.caption_projection.17.linear.weight": "./tensors/arg608.tensorbin",
    "transformer.single_transformer_blocks.9.attn.to_v.bias": "./tensors/arg610.tensorbin",
    "transformer.single_transformer_blocks.9.attn.to_v.weight": "./tensors/arg611.tensorbin",
    "transformer.single_transformer_blocks.9.attn.norm_k.weight": "./tensors/arg612.tensorbin",
    "transformer.single_transformer_blocks.9.attn.to_k.bias": "./tensors/arg613.tensorbin",
    "transformer.single_transformer_blocks.9.attn.to_k.weight": "./tensors/arg614.tensorbin",
    "transformer.single_transformer_blocks.9.attn.norm_q.weight": "./tensors/arg615.tensorbin",
    "transformer.single_transformer_blocks.9.attn.to_q.bias": "./tensors/arg616.tensorbin",
    "transformer.single_transformer_blocks.9.attn.to_q.weight": "./tensors/arg617.tensorbin",
    "transformer.caption_projection.18.linear.weight": "./tensors/arg618.tensorbin",
    "transformer.single_transformer_blocks.10.attn.to_v.bias": "./tensors/arg620.tensorbin",
    "transformer.single_transformer_blocks.10.attn.to_v.weight": "./tensors/arg621.tensorbin",
    "transformer.single_transformer_blocks.10.attn.norm_k.weight": "./tensors/arg622.tensorbin",
    "transformer.single_transformer_blocks.10.attn.to_k.bias": "./tensors/arg623.tensorbin",
    "transformer.single_transformer_blocks.10.attn.to_k.weight": "./tensors/arg624.tensorbin",
    "transformer.single_transformer_blocks.10.attn.norm_q.weight": "./tensors/arg625.tensorbin",
    "transformer.single_transformer_blocks.10.attn.to_q.bias": "./tensors/arg626.tensorbin",
    "transformer.single_transformer_blocks.10.attn.to_q.weight": "./tensors/arg627.tensorbin",
    "transformer.caption_projection.19.linear.weight": "./tensors/arg628.tensorbin",
    "transformer.single_transformer_blocks.11.attn.to_v.bias": "./tensors/arg630.tensorbin",
    "transformer.single_transformer_blocks.11.attn.to_v.weight": "./tensors/arg631.tensorbin",
    "transformer.single_transformer_blocks.11.attn.norm_k.weight": "./tensors/arg632.tensorbin",
    "transformer.single_transformer_blocks.11.attn.to_k.bias": "./tensors/arg633.tensorbin",
    "transformer.single_transformer_blocks.11.attn.to_k.weight": "./tensors/arg634.tensorbin",
    "transformer.single_transformer_blocks.11.attn.norm_q.weight": "./tensors/arg635.tensorbin",
    "transformer.single_transformer_blocks.11.attn.to_q.bias": "./tensors/arg636.tensorbin",
    "transformer.single_transformer_blocks.11.attn.to_q.weight": "./tensors/arg637.tensorbin",
    "transformer.caption_projection.20.linear.weight": "./tensors/arg638.tensorbin",
    "transformer.single_transformer_blocks.12.attn.to_v.bias": "./tensors/arg640.tensorbin",
    "transformer.single_transformer_blocks.12.attn.to_v.weight": "./tensors/arg641.tensorbin",
    "transformer.single_transformer_blocks.12.attn.norm_k.weight": "./tensors/arg642.tensorbin",
    "transformer.single_transformer_blocks.12.attn.to_k.bias": "./tensors/arg643.tensorbin",
    "transformer.single_transformer_blocks.12.attn.to_k.weight": "./tensors/arg644.tensorbin",
    "transformer.single_transformer_blocks.12.attn.norm_q.weight": "./tensors/arg645.tensorbin",
    "transformer.single_transformer_blocks.12.attn.to_q.bias": "./tensors/arg646.tensorbin",
    "transformer.single_transformer_blocks.12.attn.to_q.weight": "./tensors/arg647.tensorbin",
    "transformer.caption_projection.21.linear.weight": "./tensors/arg648.tensorbin",
    "transformer.single_transformer_blocks.13.attn.to_v.bias": "./tensors/arg650.tensorbin",
    "transformer.single_transformer_blocks.13.attn.to_v.weight": "./tensors/arg651.tensorbin",
    "transformer.single_transformer_blocks.13.attn.norm_k.weight": "./tensors/arg652.tensorbin",
    "transformer.single_transformer_blocks.13.attn.to_k.bias": "./tensors/arg653.tensorbin",
    "transformer.single_transformer_blocks.13.attn.to_k.weight": "./tensors/arg654.tensorbin",
    "transformer.single_transformer_blocks.13.attn.norm_q.weight": "./tensors/arg655.tensorbin",
    "transformer.single_transformer_blocks.13.attn.to_q.bias": "./tensors/arg656.tensorbin",
    "transformer.single_transformer_blocks.13.attn.to_q.weight": "./tensors/arg657.tensorbin",
    "transformer.caption_projection.22.linear.weight": "./tensors/arg658.tensorbin",
    "transformer.single_transformer_blocks.14.attn.to_v.bias": "./tensors/arg660.tensorbin",
    "transformer.single_transformer_blocks.14.attn.to_v.weight": "./tensors/arg661.tensorbin",
    "transformer.single_transformer_blocks.14.attn.norm_k.weight": "./tensors/arg662.tensorbin",
    "transformer.single_transformer_blocks.14.attn.to_k.bias": "./tensors/arg663.tensorbin",
    "transformer.single_transformer_blocks.14.attn.to_k.weight": "./tensors/arg664.tensorbin",
    "transformer.single_transformer_blocks.14.attn.norm_q.weight": "./tensors/arg665.tensorbin",
    "transformer.single_transformer_blocks.14.attn.to_q.bias": "./tensors/arg666.tensorbin",
    "transformer.single_transformer_blocks.14.attn.to_q.weight": "./tensors/arg667.tensorbin",
    "transformer.caption_projection.23.linear.weight": "./tensors/arg668.tensorbin",
    "transformer.single_transformer_blocks.15.attn.to_v.bias": "./tensors/arg670.tensorbin",
    "transformer.single_transformer_blocks.15.attn.to_v.weight": "./tensors/arg671.tensorbin",
    "transformer.single_transformer_blocks.15.attn.norm_k.weight": "./tensors/arg672.tensorbin",
    "transformer.single_transformer_blocks.15.attn.to_k.bias": "./tensors/arg673.tensorbin",
    "transformer.single_transformer_blocks.15.attn.to_k.weight": "./tensors/arg674.tensorbin",
    "transformer.single_transformer_blocks.15.attn.norm_q.weight": "./tensors/arg675.tensorbin",
    "transformer.single_transformer_blocks.15.attn.to_q.bias": "./tensors/arg676.tensorbin",
    "transformer.single_transformer_blocks.15.attn.to_q.weight": "./tensors/arg677.tensorbin",
    "transformer.caption_projection.24.linear.weight": "./tensors/arg678.tensorbin",
    "transformer.single_transformer_blocks.16.attn.to_v.bias": "./tensors/arg680.tensorbin",
    "transformer.single_transformer_blocks.16.attn.to_v.weight": "./tensors/arg681.tensorbin",
    "transformer.single_transformer_blocks.16.attn.norm_k.weight": "./tensors/arg682.tensorbin",
    "transformer.single_transformer_blocks.16.attn.to_k.bias": "./tensors/arg683.tensorbin",
    "transformer.single_transformer_blocks.16.attn.to_k.weight": "./tensors/arg684.tensorbin",
    "transformer.single_transformer_blocks.16.attn.norm_q.weight": "./tensors/arg685.tensorbin",
    "transformer.single_transformer_blocks.16.attn.to_q.bias": "./tensors/arg686.tensorbin",
    "transformer.single_transformer_blocks.16.attn.to_q.weight": "./tensors/arg687.tensorbin",
    "transformer.caption_projection.25.linear.weight": "./tensors/arg688.tensorbin",
    "transformer.single_transformer_blocks.17.attn.to_v.bias": "./tensors/arg690.tensorbin",
    "transformer.single_transformer_blocks.17.attn.to_v.weight": "./tensors/arg691.tensorbin",
    "transformer.single_transformer_blocks.17.attn.norm_k.weight": "./tensors/arg692.tensorbin",
    "transformer.single_transformer_blocks.17.attn.to_k.bias": "./tensors/arg693.tensorbin",
    "transformer.single_transformer_blocks.17.attn.to_k.weight": "./tensors/arg694.tensorbin",
    "transformer.single_transformer_blocks.17.attn.norm_q.weight": "./tensors/arg695.tensorbin",
    "transformer.single_transformer_blocks.17.attn.to_q.bias": "./tensors/arg696.tensorbin",
    "transformer.single_transformer_blocks.17.attn.to_q.weight": "./tensors/arg697.tensorbin",
    "transformer.caption_projection.26.linear.weight": "./tensors/arg698.tensorbin",
    "transformer.single_transformer_blocks.18.attn.to_v.bias": "./tensors/arg700.tensorbin",
    "transformer.single_transformer_blocks.18.attn.to_v.weight": "./tensors/arg701.tensorbin",
    "transformer.single_transformer_blocks.18.attn.norm_k.weight": "./tensors/arg702.tensorbin",
    "transformer.single_transformer_blocks.18.attn.to_k.bias": "./tensors/arg703.tensorbin",
    "transformer.single_transformer_blocks.18.attn.to_k.weight": "./tensors/arg704.tensorbin",
    "transformer.single_transformer_blocks.18.attn.norm_q.weight": "./tensors/arg705.tensorbin",
    "transformer.single_transformer_blocks.18.attn.to_q.bias": "./tensors/arg706.tensorbin",
    "transformer.single_transformer_blocks.18.attn.to_q.weight": "./tensors/arg707.tensorbin",
    "transformer.caption_projection.27.linear.weight": "./tensors/arg708.tensorbin",
    "transformer.single_transformer_blocks.19.attn.to_v.bias": "./tensors/arg710.tensorbin",
    "transformer.single_transformer_blocks.19.attn.to_v.weight": "./tensors/arg711.tensorbin",
    "transformer.single_transformer_blocks.19.attn.norm_k.weight": "./tensors/arg712.tensorbin",
    "transformer.single_transformer_blocks.19.attn.to_k.bias": "./tensors/arg713.tensorbin",
    "transformer.single_transformer_blocks.19.attn.to_k.weight": "./tensors/arg714.tensorbin",
    "transformer.single_transformer_blocks.19.attn.norm_q.weight": "./tensors/arg715.tensorbin",
    "transformer.single_transformer_blocks.19.attn.to_q.bias": "./tensors/arg716.tensorbin",
    "transformer.single_transformer_blocks.19.attn.to_q.weight": "./tensors/arg717.tensorbin",
    "transformer.caption_projection.28.linear.weight": "./tensors/arg718.tensorbin",
    "transformer.single_transformer_blocks.20.attn.to_v.bias": "./tensors/arg720.tensorbin",
    "transformer.single_transformer_blocks.20.attn.to_v.weight": "./tensors/arg721.tensorbin",
    "transformer.single_transformer_blocks.20.attn.norm_k.weight": "./tensors/arg722.tensorbin",
    "transformer.single_transformer_blocks.20.attn.to_k.bias": "./tensors/arg723.tensorbin",
    "transformer.single_transformer_blocks.20.attn.to_k.weight": "./tensors/arg724.tensorbin",
    "transformer.single_transformer_blocks.20.attn.norm_q.weight": "./tensors/arg725.tensorbin",
    "transformer.single_transformer_blocks.20.attn.to_q.bias": "./tensors/arg726.tensorbin",
    "transformer.single_transformer_blocks.20.attn.to_q.weight": "./tensors/arg727.tensorbin",
    "transformer.caption_projection.29.linear.weight": "./tensors/arg728.tensorbin",
    "transformer.single_transformer_blocks.21.attn.to_v.bias": "./tensors/arg730.tensorbin",
    "transformer.single_transformer_blocks.21.attn.to_v.weight": "./tensors/arg731.tensorbin",
    "transformer.single_transformer_blocks.21.attn.norm_k.weight": "./tensors/arg732.tensorbin",
    "transformer.single_transformer_blocks.21.attn.to_k.bias": "./tensors/arg733.tensorbin",
    "transformer.single_transformer_blocks.21.attn.to_k.weight": "./tensors/arg734.tensorbin",
    "transformer.single_transformer_blocks.21.attn.norm_q.weight": "./tensors/arg735.tensorbin",
    "transformer.single_transformer_blocks.21.attn.to_q.bias": "./tensors/arg736.tensorbin",
    "transformer.single_transformer_blocks.21.attn.to_q.weight": "./tensors/arg737.tensorbin",
    "transformer.caption_projection.30.linear.weight": "./tensors/arg738.tensorbin",
    "transformer.single_transformer_blocks.22.attn.to_v.bias": "./tensors/arg740.tensorbin",
    "transformer.single_transformer_blocks.22.attn.to_v.weight": "./tensors/arg741.tensorbin",
    "transformer.single_transformer_blocks.22.attn.norm_k.weight": "./tensors/arg742.tensorbin",
    "transformer.single_transformer_blocks.22.attn.to_k.bias": "./tensors/arg743.tensorbin",
    "transformer.single_transformer_blocks.22.attn.to_k.weight": "./tensors/arg744.tensorbin",
    "transformer.single_transformer_blocks.22.attn.norm_q.weight": "./tensors/arg745.tensorbin",
    "transformer.single_transformer_blocks.22.attn.to_q.bias": "./tensors/arg746.tensorbin",
    "transformer.single_transformer_blocks.22.attn.to_q.weight": "./tensors/arg747.tensorbin",
    "transformer.caption_projection.31.linear.weight": "./tensors/arg748.tensorbin",
    "transformer.single_transformer_blocks.23.attn.to_v.bias": "./tensors/arg750.tensorbin",
    "transformer.single_transformer_blocks.23.attn.to_v.weight": "./tensors/arg751.tensorbin",
    "transformer.single_transformer_blocks.23.attn.norm_k.weight": "./tensors/arg752.tensorbin",
    "transformer.single_transformer_blocks.23.attn.to_k.bias": "./tensors/arg753.tensorbin",
    "transformer.single_transformer_blocks.23.attn.to_k.weight": "./tensors/arg754.tensorbin",
    "transformer.single_transformer_blocks.23.attn.norm_q.weight": "./tensors/arg755.tensorbin",
    "transformer.single_transformer_blocks.23.attn.to_q.bias": "./tensors/arg756.tensorbin",
    "transformer.single_transformer_blocks.23.attn.to_q.weight": "./tensors/arg757.tensorbin",
    "transformer.caption_projection.32.linear.weight": "./tensors/arg758.tensorbin",
    "transformer.single_transformer_blocks.24.attn.to_v.bias": "./tensors/arg760.tensorbin",
    "transformer.single_transformer_blocks.24.attn.to_v.weight": "./tensors/arg761.tensorbin",
    "transformer.single_transformer_blocks.24.attn.norm_k.weight": "./tensors/arg762.tensorbin",
    "transformer.single_transformer_blocks.24.attn.to_k.bias": "./tensors/arg763.tensorbin",
    "transformer.single_transformer_blocks.24.attn.to_k.weight": "./tensors/arg764.tensorbin",
    "transformer.single_transformer_blocks.24.attn.norm_q.weight": "./tensors/arg765.tensorbin",
    "transformer.single_transformer_blocks.24.attn.to_q.bias": "./tensors/arg766.tensorbin",
    "transformer.single_transformer_blocks.24.attn.to_q.weight": "./tensors/arg767.tensorbin",
    "transformer.caption_projection.33.linear.weight": "./tensors/arg768.tensorbin",
    "transformer.single_transformer_blocks.25.attn.to_v.bias": "./tensors/arg770.tensorbin",
    "transformer.single_transformer_blocks.25.attn.to_v.weight": "./tensors/arg771.tensorbin",
    "transformer.single_transformer_blocks.25.attn.norm_k.weight": "./tensors/arg772.tensorbin",
    "transformer.single_transformer_blocks.25.attn.to_k.bias": "./tensors/arg773.tensorbin",
    "transformer.single_transformer_blocks.25.attn.to_k.weight": "./tensors/arg774.tensorbin",
    "transformer.single_transformer_blocks.25.attn.norm_q.weight": "./tensors/arg775.tensorbin",
    "transformer.single_transformer_blocks.25.attn.to_q.bias": "./tensors/arg776.tensorbin",
    "transformer.single_transformer_blocks.25.attn.to_q.weight": "./tensors/arg777.tensorbin",
    "transformer.caption_projection.34.linear.weight": "./tensors/arg778.tensorbin",
    "transformer.single_transformer_blocks.26.attn.to_v.bias": "./tensors/arg780.tensorbin",
    "transformer.single_transformer_blocks.26.attn.to_v.weight": "./tensors/arg781.tensorbin",
    "transformer.single_transformer_blocks.26.attn.norm_k.weight": "./tensors/arg782.tensorbin",
    "transformer.single_transformer_blocks.26.attn.to_k.bias": "./tensors/arg783.tensorbin",
    "transformer.single_transformer_blocks.26.attn.to_k.weight": "./tensors/arg784.tensorbin",
    "transformer.single_transformer_blocks.26.attn.norm_q.weight": "./tensors/arg785.tensorbin",
    "transformer.single_transformer_blocks.26.attn.to_q.bias": "./tensors/arg786.tensorbin",
    "transformer.single_transformer_blocks.26.attn.to_q.weight": "./tensors/arg787.tensorbin",
    "transformer.caption_projection.35.linear.weight": "./tensors/arg788.tensorbin",
    "transformer.single_transformer_blocks.27.attn.to_v.bias": "./tensors/arg790.tensorbin",
    "transformer.single_transformer_blocks.27.attn.to_v.weight": "./tensors/arg791.tensorbin",
    "transformer.single_transformer_blocks.27.attn.norm_k.weight": "./tensors/arg792.tensorbin",
    "transformer.single_transformer_blocks.27.attn.to_k.bias": "./tensors/arg793.tensorbin",
    "transformer.single_transformer_blocks.27.attn.to_k.weight": "./tensors/arg794.tensorbin",
    "transformer.single_transformer_blocks.27.attn.norm_q.weight": "./tensors/arg795.tensorbin",
    "transformer.single_transformer_blocks.27.attn.to_q.bias": "./tensors/arg796.tensorbin",
    "transformer.single_transformer_blocks.27.attn.to_q.weight": "./tensors/arg797.tensorbin",
    "transformer.caption_projection.36.linear.weight": "./tensors/arg798.tensorbin",
    "transformer.single_transformer_blocks.28.attn.to_v.bias": "./tensors/arg800.tensorbin",
    "transformer.single_transformer_blocks.28.attn.to_v.weight": "./tensors/arg801.tensorbin",
    "transformer.single_transformer_blocks.28.attn.norm_k.weight": "./tensors/arg802.tensorbin",
    "transformer.single_transformer_blocks.28.attn.to_k.bias": "./tensors/arg803.tensorbin",
    "transformer.single_transformer_blocks.28.attn.to_k.weight": "./tensors/arg804.tensorbin",
    "transformer.single_transformer_blocks.28.attn.norm_q.weight": "./tensors/arg805.tensorbin",
    "transformer.single_transformer_blocks.28.attn.to_q.bias": "./tensors/arg806.tensorbin",
    "transformer.single_transformer_blocks.28.attn.to_q.weight": "./tensors/arg807.tensorbin",
    "transformer.caption_projection.37.linear.weight": "./tensors/arg808.tensorbin",
    "transformer.single_transformer_blocks.29.attn.to_v.bias": "./tensors/arg810.tensorbin",
    "transformer.single_transformer_blocks.29.attn.to_v.weight": "./tensors/arg811.tensorbin",
    "transformer.single_transformer_blocks.29.attn.norm_k.weight": "./tensors/arg812.tensorbin",
    "transformer.single_transformer_blocks.29.attn.to_k.bias": "./tensors/arg813.tensorbin",
    "transformer.single_transformer_blocks.29.attn.to_k.weight": "./tensors/arg814.tensorbin",
    "transformer.single_transformer_blocks.29.attn.norm_q.weight": "./tensors/arg815.tensorbin",
    "transformer.single_transformer_blocks.29.attn.to_q.bias": "./tensors/arg816.tensorbin",
    "transformer.single_transformer_blocks.29.attn.to_q.weight": "./tensors/arg817.tensorbin",
    "transformer.caption_projection.38.linear.weight": "./tensors/arg818.tensorbin",
    "transformer.single_transformer_blocks.30.attn.to_v.bias": "./tensors/arg820.tensorbin",
    "transformer.single_transformer_blocks.30.attn.to_v.weight": "./tensors/arg821.tensorbin",
    "transformer.single_transformer_blocks.30.attn.norm_k.weight": "./tensors/arg822.tensorbin",
    "transformer.single_transformer_blocks.30.attn.to_k.bias": "./tensors/arg823.tensorbin",
    "transformer.single_transformer_blocks.30.attn.to_k.weight": "./tensors/arg824.tensorbin",
    "transformer.single_transformer_blocks.30.attn.norm_q.weight": "./tensors/arg825.tensorbin",
    "transformer.single_transformer_blocks.30.attn.to_q.bias": "./tensors/arg826.tensorbin",
    "transformer.single_transformer_blocks.30.attn.to_q.weight": "./tensors/arg827.tensorbin",
    "transformer.caption_projection.39.linear.weight": "./tensors/arg828.tensorbin",
    "transformer.single_transformer_blocks.31.attn.to_v.bias": "./tensors/arg830.tensorbin",
    "transformer.single_transformer_blocks.31.attn.to_v.weight": "./tensors/arg831.tensorbin",
    "transformer.single_transformer_blocks.31.attn.norm_k.weight": "./tensors/arg832.tensorbin",
    "transformer.single_transformer_blocks.31.attn.to_k.bias": "./tensors/arg833.tensorbin",
    "transformer.single_transformer_blocks.31.attn.to_k.weight": "./tensors/arg834.tensorbin",
    "transformer.single_transformer_blocks.31.attn.norm_q.weight": "./tensors/arg835.tensorbin",
    "transformer.single_transformer_blocks.31.attn.to_q.bias": "./tensors/arg836.tensorbin",
    "transformer.single_transformer_blocks.31.attn.to_q.weight": "./tensors/arg837.tensorbin",
    "transformer.caption_projection.40.linear.weight": "./tensors/arg838.tensorbin",
    "transformer.single_transformer_blocks.32.attn.to_v.bias": "./tensors/arg840.tensorbin",
    "transformer.single_transformer_blocks.32.attn.to_v.weight": "./tensors/arg841.tensorbin",
    "transformer.single_transformer_blocks.32.attn.norm_k.weight": "./tensors/arg842.tensorbin",
    "transformer.single_transformer_blocks.32.attn.to_k.bias": "./tensors/arg843.tensorbin",
    "transformer.single_transformer_blocks.32.attn.to_k.weight": "./tensors/arg844.tensorbin",
    "transformer.single_transformer_blocks.32.attn.norm_q.weight": "./tensors/arg845.tensorbin",
    "transformer.single_transformer_blocks.32.attn.to_q.bias": "./tensors/arg846.tensorbin",
    "transformer.single_transformer_blocks.32.attn.to_q.weight": "./tensors/arg847.tensorbin",
    "transformer.caption_projection.41.linear.weight": "./tensors/arg848.tensorbin",
    "transformer.single_transformer_blocks.33.attn.to_v.bias": "./tensors/arg850.tensorbin",
    "transformer.single_transformer_blocks.33.attn.to_v.weight": "./tensors/arg851.tensorbin",
    "transformer.single_transformer_blocks.33.attn.norm_k.weight": "./tensors/arg852.tensorbin",
    "transformer.single_transformer_blocks.33.attn.to_k.bias": "./tensors/arg853.tensorbin",
    "transformer.single_transformer_blocks.33.attn.to_k.weight": "./tensors/arg854.tensorbin",
    "transformer.single_transformer_blocks.33.attn.norm_q.weight": "./tensors/arg855.tensorbin",
    "transformer.single_transformer_blocks.33.attn.to_q.bias": "./tensors/arg856.tensorbin",
    "transformer.single_transformer_blocks.33.attn.to_q.weight": "./tensors/arg857.tensorbin",
    "transformer.caption_projection.42.linear.weight": "./tensors/arg858.tensorbin",
    "transformer.single_transformer_blocks.34.attn.to_v.bias": "./tensors/arg860.tensorbin",
    "transformer.single_transformer_blocks.34.attn.to_v.weight": "./tensors/arg861.tensorbin",
    "transformer.single_transformer_blocks.34.attn.norm_k.weight": "./tensors/arg862.tensorbin",
    "transformer.single_transformer_blocks.34.attn.to_k.bias": "./tensors/arg863.tensorbin",
    "transformer.single_transformer_blocks.34.attn.to_k.weight": "./tensors/arg864.tensorbin",
    "transformer.single_transformer_blocks.34.attn.norm_q.weight": "./tensors/arg865.tensorbin",
    "transformer.single_transformer_blocks.34.attn.to_q.bias": "./tensors/arg866.tensorbin",
    "transformer.single_transformer_blocks.34.attn.to_q.weight": "./tensors/arg867.tensorbin",
    "transformer.caption_projection.43.linear.weight": "./tensors/arg868.tensorbin",
    "transformer.single_transformer_blocks.35.attn.to_v.bias": "./tensors/arg870.tensorbin",
    "transformer.single_transformer_blocks.35.attn.to_v.weight": "./tensors/arg871.tensorbin",
    "transformer.single_transformer_blocks.35.attn.norm_k.weight": "./tensors/arg872.tensorbin",
    "transformer.single_transformer_blocks.35.attn.to_k.bias": "./tensors/arg873.tensorbin",
    "transformer.single_transformer_blocks.35.attn.to_k.weight": "./tensors/arg874.tensorbin",
    "transformer.single_transformer_blocks.35.attn.norm_q.weight": "./tensors/arg875.tensorbin",
    "transformer.single_transformer_blocks.35.attn.to_q.bias": "./tensors/arg876.tensorbin",
    "transformer.single_transformer_blocks.35.attn.to_q.weight": "./tensors/arg877.tensorbin",
    "transformer.caption_projection.44.linear.weight": "./tensors/arg878.tensorbin",
    "transformer.single_transformer_blocks.36.attn.to_v.bias": "./tensors/arg880.tensorbin",
    "transformer.single_transformer_blocks.36.attn.to_v.weight": "./tensors/arg881.tensorbin",
    "transformer.single_transformer_blocks.36.attn.norm_k.weight": "./tensors/arg882.tensorbin",
    "transformer.single_transformer_blocks.36.attn.to_k.bias": "./tensors/arg883.tensorbin",
    "transformer.single_transformer_blocks.36.attn.to_k.weight": "./tensors/arg884.tensorbin",
    "transformer.single_transformer_blocks.36.attn.norm_q.weight": "./tensors/arg885.tensorbin",
    "transformer.single_transformer_blocks.36.attn.to_q.bias": "./tensors/arg886.tensorbin",
    "transformer.single_transformer_blocks.36.attn.to_q.weight": "./tensors/arg887.tensorbin",
    "transformer.caption_projection.45.linear.weight": "./tensors/arg888.tensorbin",
    "transformer.single_transformer_blocks.37.attn.to_v.bias": "./tensors/arg890.tensorbin",
    "transformer.single_transformer_blocks.37.attn.to_v.weight": "./tensors/arg891.tensorbin",
    "transformer.single_transformer_blocks.37.attn.norm_k.weight": "./tensors/arg892.tensorbin",
    "transformer.single_transformer_blocks.37.attn.to_k.bias": "./tensors/arg893.tensorbin",
    "transformer.single_transformer_blocks.37.attn.to_k.weight": "./tensors/arg894.tensorbin",
    "transformer.single_transformer_blocks.37.attn.norm_q.weight": "./tensors/arg895.tensorbin",
    "transformer.single_transformer_blocks.37.attn.to_q.bias": "./tensors/arg896.tensorbin",
    "transformer.single_transformer_blocks.37.attn.to_q.weight": "./tensors/arg897.tensorbin",
}


ON_DEVICE_WEIGHTS = {
    "transformer.caption_projection.0.linear.weight",
    "transformer.caption_projection.1.linear.weight",
    "transformer.caption_projection.10.linear.weight",
    "transformer.caption_projection.11.linear.weight",
    "transformer.caption_projection.12.linear.weight",
    "transformer.caption_projection.13.linear.weight",
    "transformer.caption_projection.14.linear.weight",
    "transformer.caption_projection.15.linear.weight",
    "transformer.caption_projection.16.linear.weight",
    "transformer.caption_projection.17.linear.weight",
    "transformer.caption_projection.18.linear.weight",
    "transformer.caption_projection.19.linear.weight",
    "transformer.caption_projection.2.linear.weight",
    "transformer.caption_projection.20.linear.weight",
    "transformer.caption_projection.21.linear.weight",
    "transformer.caption_projection.22.linear.weight",
    "transformer.caption_projection.23.linear.weight",
    "transformer.caption_projection.24.linear.weight",
    "transformer.caption_projection.25.linear.weight",
    "transformer.caption_projection.26.linear.weight",
    "transformer.caption_projection.27.linear.weight",
    "transformer.caption_projection.28.linear.weight",
    "transformer.caption_projection.29.linear.weight",
    "transformer.caption_projection.3.linear.weight",
    "transformer.caption_projection.30.linear.weight",
    "transformer.caption_projection.31.linear.weight",
    "transformer.caption_projection.32.linear.weight",
    "transformer.caption_projection.33.linear.weight",
    "transformer.caption_projection.34.linear.weight",
    "transformer.caption_projection.35.linear.weight",
    "transformer.caption_projection.36.linear.weight",
    "transformer.caption_projection.37.linear.weight",
    "transformer.caption_projection.38.linear.weight",
    "transformer.caption_projection.39.linear.weight",
    "transformer.caption_projection.4.linear.weight",
    "transformer.caption_projection.40.linear.weight",
    "transformer.caption_projection.41.linear.weight",
    "transformer.caption_projection.42.linear.weight",
    "transformer.caption_projection.43.linear.weight",
    "transformer.caption_projection.44.linear.weight",
    "transformer.caption_projection.45.linear.weight",
    "transformer.caption_projection.5.linear.weight",
    "transformer.caption_projection.6.linear.weight",
    "transformer.caption_projection.7.linear.weight",
    "transformer.caption_projection.8.linear.weight",
    "transformer.caption_projection.9.linear.weight",
    "transformer.context_embedder.bias",
    "transformer.context_embedder.weight",
    "transformer.proj_out.bias",
    "transformer.proj_out.weight",
    "transformer.single_transformer_blocks.0.attn.norm_k.weight",
    "transformer.single_transformer_blocks.0.attn.norm_q.weight",
    "transformer.single_transformer_blocks.0.proj_out.weight",
    "transformer.single_transformer_blocks.1.attn.norm_k.weight",
    "transformer.single_transformer_blocks.1.attn.norm_q.weight",
    "transformer.single_transformer_blocks.1.proj_out.weight",
    "transformer.single_transformer_blocks.10.attn.norm_k.weight",
    "transformer.single_transformer_blocks.10.attn.norm_q.weight",
    "transformer.single_transformer_blocks.10.proj_out.weight",
    "transformer.single_transformer_blocks.11.attn.norm_k.weight",
    "transformer.single_transformer_blocks.11.attn.norm_q.weight",
    "transformer.single_transformer_blocks.11.proj_out.weight",
    "transformer.single_transformer_blocks.12.attn.norm_k.weight",
    "transformer.single_transformer_blocks.12.attn.norm_q.weight",
    "transformer.single_transformer_blocks.12.proj_out.weight",
    "transformer.single_transformer_blocks.13.attn.norm_k.weight",
    "transformer.single_transformer_blocks.13.attn.norm_q.weight",
    "transformer.single_transformer_blocks.13.proj_out.weight",
    "transformer.single_transformer_blocks.14.attn.norm_k.weight",
    "transformer.single_transformer_blocks.14.attn.norm_q.weight",
    "transformer.single_transformer_blocks.14.proj_out.weight",
    "transformer.single_transformer_blocks.15.attn.norm_k.weight",
    "transformer.single_transformer_blocks.15.attn.norm_q.weight",
    "transformer.single_transformer_blocks.15.proj_out.weight",
    "transformer.single_transformer_blocks.16.attn.norm_k.weight",
    "transformer.single_transformer_blocks.16.attn.norm_q.weight",
    "transformer.single_transformer_blocks.16.proj_out.weight",
    "transformer.single_transformer_blocks.17.attn.norm_k.weight",
    "transformer.single_transformer_blocks.17.attn.norm_q.weight",
    "transformer.single_transformer_blocks.17.proj_out.weight",
    "transformer.single_transformer_blocks.18.attn.norm_k.weight",
    "transformer.single_transformer_blocks.18.attn.norm_q.weight",
    "transformer.single_transformer_blocks.18.proj_out.weight",
    "transformer.single_transformer_blocks.19.attn.norm_k.weight",
    "transformer.single_transformer_blocks.19.attn.norm_q.weight",
    "transformer.single_transformer_blocks.19.proj_out.weight",
    "transformer.single_transformer_blocks.2.attn.norm_k.weight",
    "transformer.single_transformer_blocks.2.attn.norm_q.weight",
    "transformer.single_transformer_blocks.2.proj_out.weight",
    "transformer.single_transformer_blocks.20.attn.norm_k.weight",
    "transformer.single_transformer_blocks.20.attn.norm_q.weight",
    "transformer.single_transformer_blocks.20.proj_out.weight",
    "transformer.single_transformer_blocks.21.attn.norm_k.weight",
    "transformer.single_transformer_blocks.21.attn.norm_q.weight",
    "transformer.single_transformer_blocks.21.proj_out.weight",
    "transformer.single_transformer_blocks.22.attn.norm_k.weight",
    "transformer.single_transformer_blocks.22.attn.norm_q.weight",
    "transformer.single_transformer_blocks.22.proj_out.weight",
    "transformer.single_transformer_blocks.23.attn.norm_k.weight",
    "transformer.single_transformer_blocks.23.attn.norm_q.weight",
    "transformer.single_transformer_blocks.23.proj_out.weight",
    "transformer.single_transformer_blocks.24.attn.norm_k.weight",
    "transformer.single_transformer_blocks.24.attn.norm_q.weight",
    "transformer.single_transformer_blocks.24.proj_out.weight",
    "transformer.single_transformer_blocks.25.attn.norm_k.weight",
    "transformer.single_transformer_blocks.25.attn.norm_q.weight",
    "transformer.single_transformer_blocks.25.proj_out.weight",
    "transformer.single_transformer_blocks.26.attn.norm_k.weight",
    "transformer.single_transformer_blocks.26.attn.norm_q.weight",
    "transformer.single_transformer_blocks.26.proj_out.weight",
    "transformer.single_transformer_blocks.27.attn.norm_k.weight",
    "transformer.single_transformer_blocks.27.attn.norm_q.weight",
    "transformer.single_transformer_blocks.27.proj_out.weight",
    "transformer.single_transformer_blocks.28.attn.norm_k.weight",
    "transformer.single_transformer_blocks.28.attn.norm_q.weight",
    "transformer.single_transformer_blocks.28.proj_out.weight",
    "transformer.single_transformer_blocks.29.attn.norm_k.weight",
    "transformer.single_transformer_blocks.29.attn.norm_q.weight",
    "transformer.single_transformer_blocks.29.proj_out.weight",
    "transformer.single_transformer_blocks.3.attn.norm_k.weight",
    "transformer.single_transformer_blocks.3.attn.norm_q.weight",
    "transformer.single_transformer_blocks.3.proj_out.weight",
    "transformer.single_transformer_blocks.30.attn.norm_k.weight",
    "transformer.single_transformer_blocks.30.attn.norm_q.weight",
    "transformer.single_transformer_blocks.30.proj_out.weight",
    "transformer.single_transformer_blocks.31.attn.norm_k.weight",
    "transformer.single_transformer_blocks.31.attn.norm_q.weight",
    "transformer.single_transformer_blocks.31.proj_out.weight",
    "transformer.single_transformer_blocks.32.attn.norm_k.weight",
    "transformer.single_transformer_blocks.32.attn.norm_q.weight",
    "transformer.single_transformer_blocks.32.proj_out.weight",
    "transformer.single_transformer_blocks.33.attn.norm_k.weight",
    "transformer.single_transformer_blocks.33.attn.norm_q.weight",
    "transformer.single_transformer_blocks.33.proj_out.weight",
    "transformer.single_transformer_blocks.34.attn.norm_k.weight",
    "transformer.single_transformer_blocks.34.attn.norm_q.weight",
    "transformer.single_transformer_blocks.34.proj_out.weight",
    "transformer.single_transformer_blocks.35.attn.norm_k.weight",
    "transformer.single_transformer_blocks.35.attn.norm_q.weight",
    "transformer.single_transformer_blocks.35.proj_out.weight",
    "transformer.single_transformer_blocks.36.attn.norm_k.weight",
    "transformer.single_transformer_blocks.36.attn.norm_q.weight",
    "transformer.single_transformer_blocks.36.proj_out.weight",
    "transformer.single_transformer_blocks.37.attn.norm_k.weight",
    "transformer.single_transformer_blocks.37.attn.norm_q.weight",
    "transformer.single_transformer_blocks.37.proj_out.weight",
    "transformer.single_transformer_blocks.4.attn.norm_k.weight",
    "transformer.single_transformer_blocks.4.attn.norm_q.weight",
    "transformer.single_transformer_blocks.4.proj_out.weight",
    "transformer.single_transformer_blocks.5.attn.norm_k.weight",
    "transformer.single_transformer_blocks.5.attn.norm_q.weight",
    "transformer.single_transformer_blocks.5.proj_out.weight",
    "transformer.single_transformer_blocks.6.attn.norm_k.weight",
    "transformer.single_transformer_blocks.6.attn.norm_q.weight",
    "transformer.single_transformer_blocks.6.proj_out.weight",
    "transformer.single_transformer_blocks.7.attn.norm_k.weight",
    "transformer.single_transformer_blocks.7.attn.norm_q.weight",
    "transformer.single_transformer_blocks.7.proj_out.weight",
    "transformer.single_transformer_blocks.8.attn.norm_k.weight",
    "transformer.single_transformer_blocks.8.attn.norm_q.weight",
    "transformer.single_transformer_blocks.8.proj_out.weight",
    "transformer.single_transformer_blocks.9.attn.norm_k.weight",
    "transformer.single_transformer_blocks.9.attn.norm_q.weight",
    "transformer.single_transformer_blocks.9.proj_out.weight",
    "transformer.transformer_blocks.0.attn.norm_added_k.weight",
    "transformer.transformer_blocks.0.attn.norm_added_q.weight",
    "transformer.transformer_blocks.0.attn.norm_k.weight",
    "transformer.transformer_blocks.0.attn.norm_q.weight",
    "transformer.transformer_blocks.0.attn.to_add_out.weight",
    "transformer.transformer_blocks.0.attn.to_out.0.weight",
    "transformer.transformer_blocks.0.ff.net.0.proj.bias",
    "transformer.transformer_blocks.0.ff.net.0.proj.weight",
    "transformer.transformer_blocks.0.ff.net.2.weight",
    "transformer.transformer_blocks.0.ff_context.net.0.proj.bias",
    "transformer.transformer_blocks.0.ff_context.net.0.proj.weight",
    "transformer.transformer_blocks.0.ff_context.net.2.weight",
    "transformer.transformer_blocks.1.attn.norm_added_k.weight",
    "transformer.transformer_blocks.1.attn.norm_added_q.weight",
    "transformer.transformer_blocks.1.attn.norm_k.weight",
    "transformer.transformer_blocks.1.attn.norm_q.weight",
    "transformer.transformer_blocks.1.attn.to_add_out.weight",
    "transformer.transformer_blocks.1.attn.to_out.0.weight",
    "transformer.transformer_blocks.1.ff.net.0.proj.bias",
    "transformer.transformer_blocks.1.ff.net.0.proj.weight",
    "transformer.transformer_blocks.1.ff.net.2.weight",
    "transformer.transformer_blocks.1.ff_context.net.0.proj.bias",
    "transformer.transformer_blocks.1.ff_context.net.0.proj.weight",
    "transformer.transformer_blocks.1.ff_context.net.2.weight",
    "transformer.transformer_blocks.2.attn.norm_added_k.weight",
    "transformer.transformer_blocks.2.attn.norm_added_q.weight",
    "transformer.transformer_blocks.2.attn.norm_k.weight",
    "transformer.transformer_blocks.2.attn.norm_q.weight",
    "transformer.transformer_blocks.2.attn.to_add_out.weight",
    "transformer.transformer_blocks.2.attn.to_out.0.weight",
    "transformer.transformer_blocks.2.ff.net.0.proj.bias",
    "transformer.transformer_blocks.2.ff.net.0.proj.weight",
    "transformer.transformer_blocks.2.ff.net.2.weight",
    "transformer.transformer_blocks.2.ff_context.net.0.proj.bias",
    "transformer.transformer_blocks.2.ff_context.net.0.proj.weight",
    "transformer.transformer_blocks.2.ff_context.net.2.weight",
    "transformer.transformer_blocks.3.attn.norm_added_k.weight",
    "transformer.transformer_blocks.3.attn.norm_added_q.weight",
    "transformer.transformer_blocks.3.attn.norm_k.weight",
    "transformer.transformer_blocks.3.attn.norm_q.weight",
    "transformer.transformer_blocks.3.attn.to_add_out.weight",
    "transformer.transformer_blocks.3.attn.to_out.0.weight",
    "transformer.transformer_blocks.3.ff.net.0.proj.bias",
    "transformer.transformer_blocks.3.ff.net.0.proj.weight",
    "transformer.transformer_blocks.3.ff.net.2.weight",
    "transformer.transformer_blocks.3.ff_context.net.0.proj.bias",
    "transformer.transformer_blocks.3.ff_context.net.0.proj.weight",
    "transformer.transformer_blocks.3.ff_context.net.2.weight",
    "transformer.transformer_blocks.4.attn.norm_added_k.weight",
    "transformer.transformer_blocks.4.attn.norm_added_q.weight",
    "transformer.transformer_blocks.4.attn.norm_k.weight",
    "transformer.transformer_blocks.4.attn.norm_q.weight",
    "transformer.transformer_blocks.4.attn.to_add_out.weight",
    "transformer.transformer_blocks.4.attn.to_out.0.weight",
    "transformer.transformer_blocks.4.ff.net.0.proj.bias",
    "transformer.transformer_blocks.4.ff.net.0.proj.weight",
    "transformer.transformer_blocks.4.ff.net.2.weight",
    "transformer.transformer_blocks.4.ff_context.net.0.proj.bias",
    "transformer.transformer_blocks.4.ff_context.net.0.proj.weight",
    "transformer.transformer_blocks.4.ff_context.net.2.weight",
    "transformer.transformer_blocks.5.attn.norm_added_k.weight",
    "transformer.transformer_blocks.5.attn.norm_added_q.weight",
    "transformer.transformer_blocks.5.attn.norm_k.weight",
    "transformer.transformer_blocks.5.attn.norm_q.weight",
    "transformer.transformer_blocks.5.attn.to_add_out.weight",
    "transformer.transformer_blocks.5.attn.to_out.0.weight",
    "transformer.transformer_blocks.5.ff.net.0.proj.bias",
    "transformer.transformer_blocks.5.ff.net.0.proj.weight",
    "transformer.transformer_blocks.5.ff.net.2.weight",
    "transformer.transformer_blocks.5.ff_context.net.0.proj.bias",
    "transformer.transformer_blocks.5.ff_context.net.0.proj.weight",
    "transformer.transformer_blocks.5.ff_context.net.2.weight",
    "transformer.transformer_blocks.6.attn.norm_added_k.weight",
    "transformer.transformer_blocks.6.attn.norm_added_q.weight",
    "transformer.transformer_blocks.6.attn.norm_k.weight",
    "transformer.transformer_blocks.6.attn.norm_q.weight",
    "transformer.transformer_blocks.6.attn.to_add_out.weight",
    "transformer.transformer_blocks.6.attn.to_out.0.weight",
    "transformer.transformer_blocks.6.ff.net.0.proj.bias",
    "transformer.transformer_blocks.6.ff.net.0.proj.weight",
    "transformer.transformer_blocks.6.ff.net.2.weight",
    "transformer.transformer_blocks.6.ff_context.net.0.proj.bias",
    "transformer.transformer_blocks.6.ff_context.net.0.proj.weight",
    "transformer.transformer_blocks.6.ff_context.net.2.weight",
    "transformer.transformer_blocks.7.attn.norm_added_k.weight",
    "transformer.transformer_blocks.7.attn.norm_added_q.weight",
    "transformer.transformer_blocks.7.attn.norm_k.weight",
    "transformer.transformer_blocks.7.attn.norm_q.weight",
    "transformer.transformer_blocks.7.attn.to_add_out.weight",
    "transformer.transformer_blocks.7.attn.to_out.0.weight",
    "transformer.transformer_blocks.7.ff.net.0.proj.bias",
    "transformer.transformer_blocks.7.ff.net.0.proj.weight",
    "transformer.transformer_blocks.7.ff.net.2.weight",
    "transformer.transformer_blocks.7.ff_context.net.0.proj.bias",
    "transformer.transformer_blocks.7.ff_context.net.0.proj.weight",
    "transformer.transformer_blocks.7.ff_context.net.2.weight",
    "transformer.x_embedder.bias",
    "transformer.x_embedder.weight",
}


def load_weights_for__main():
    device = utils.DeviceGetter.get_device(
        (1, 4), fabric_config=ttnn.FabricConfig.FABRIC_1D_RING
    )
    weights = {}
    for key, file_path in WEIGHT_FILE_MAP.items():
        if key in ON_DEVICE_WEIGHTS:
            weights[key] = utils.load_tensor(
                file_path,
                ttnn.Layout.TILE,
                ttnn.DataType.BFLOAT16,
                device,
                ttnn.DRAM_MEMORY_CONFIG,
            )
        else:
            weights[key] = utils.load_tensor(
                file_path,
                ttnn.Layout.ROW_MAJOR,
                ttnn.DataType.BFLOAT16,
                None,
                None,
            )
    return weights


def load_weights_for__main_from_state_dict():
    device = utils.DeviceGetter.get_device(
        (1, 4), fabric_config=ttnn.FabricConfig.FABRIC_1D_RING
    )
    model = model_pt.load_pytorch_model()
    sd = dict(model.state_dict())
    for name, buf in model.named_buffers():
        if name not in sd:
            sd[name] = buf

    weights = {}
    for key in WEIGHT_FILE_MAP:
        ttnn_tensor = ttnn.from_torch(sd[key])

        if key in ON_DEVICE_WEIGHTS:
            ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.TILE)
            ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.BFLOAT16)
            ttnn_tensor = ttnn.to_device(ttnn_tensor, device, ttnn.DRAM_MEMORY_CONFIG)
        else:
            ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.ROW_MAJOR)
            ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.BFLOAT16)

        weights[key] = ttnn_tensor
    return weights
