import ttnn
import torch
import utils
import model_pt


ALL_WEIGHTS = [
    ("classifier.1.bias", "./tensors/arg0.tensorbin"),
    ("classifier.1.weight", "./tensors/arg1.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.shortcut.normalization.running_var", "./tensors/arg2.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.shortcut.normalization.running_mean", "./tensors/arg3.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.shortcut.normalization.bias", "./tensors/arg4.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.shortcut.normalization.weight", "./tensors/arg5.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.shortcut.convolution.weight", "./tensors/arg6.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.shortcut.normalization.running_var", "./tensors/arg7.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.shortcut.normalization.running_mean", "./tensors/arg8.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.shortcut.normalization.bias", "./tensors/arg9.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.shortcut.normalization.weight", "./tensors/arg10.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.shortcut.convolution.weight", "./tensors/arg11.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.shortcut.normalization.running_var", "./tensors/arg12.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.shortcut.normalization.running_mean", "./tensors/arg13.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.shortcut.normalization.bias", "./tensors/arg14.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.shortcut.normalization.weight", "./tensors/arg15.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.shortcut.convolution.weight", "./tensors/arg16.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.shortcut.normalization.running_var", "./tensors/arg17.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.shortcut.normalization.running_mean", "./tensors/arg18.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.shortcut.normalization.bias", "./tensors/arg19.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.shortcut.normalization.weight", "./tensors/arg20.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.shortcut.convolution.weight", "./tensors/arg21.tensorbin"),
    ("resnet.embedder.embedder.normalization.running_var", "./tensors/arg22.tensorbin"),
    ("resnet.embedder.embedder.normalization.running_mean", "./tensors/arg23.tensorbin"),
    ("resnet.embedder.embedder.normalization.bias", "./tensors/arg24.tensorbin"),
    ("resnet.embedder.embedder.normalization.weight", "./tensors/arg25.tensorbin"),
    ("resnet.embedder.embedder.convolution.weight", "./tensors/arg26.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.2.normalization.running_var", "./tensors/arg28.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.2.normalization.running_mean", "./tensors/arg29.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.2.normalization.bias", "./tensors/arg30.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.2.normalization.weight", "./tensors/arg31.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.2.convolution.weight", "./tensors/arg32.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.1.normalization.running_var", "./tensors/arg33.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.1.normalization.running_mean", "./tensors/arg34.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.1.normalization.bias", "./tensors/arg35.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.1.normalization.weight", "./tensors/arg36.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.1.convolution.weight", "./tensors/arg37.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.0.normalization.running_var", "./tensors/arg38.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.0.normalization.running_mean", "./tensors/arg39.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.0.normalization.bias", "./tensors/arg40.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.0.normalization.weight", "./tensors/arg41.tensorbin"),
    ("resnet.encoder.stages.0.layers.0.layer.0.convolution.weight", "./tensors/arg42.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.2.normalization.running_var", "./tensors/arg43.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.2.normalization.running_mean", "./tensors/arg44.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.2.normalization.bias", "./tensors/arg45.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.2.normalization.weight", "./tensors/arg46.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.2.convolution.weight", "./tensors/arg47.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.1.normalization.running_var", "./tensors/arg48.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.1.normalization.running_mean", "./tensors/arg49.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.1.normalization.bias", "./tensors/arg50.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.1.normalization.weight", "./tensors/arg51.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.1.convolution.weight", "./tensors/arg52.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.0.normalization.running_var", "./tensors/arg53.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.0.normalization.running_mean", "./tensors/arg54.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.0.normalization.bias", "./tensors/arg55.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.0.normalization.weight", "./tensors/arg56.tensorbin"),
    ("resnet.encoder.stages.0.layers.1.layer.0.convolution.weight", "./tensors/arg57.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.2.normalization.running_var", "./tensors/arg58.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.2.normalization.running_mean", "./tensors/arg59.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.2.normalization.bias", "./tensors/arg60.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.2.normalization.weight", "./tensors/arg61.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.2.convolution.weight", "./tensors/arg62.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.1.normalization.running_var", "./tensors/arg63.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.1.normalization.running_mean", "./tensors/arg64.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.1.normalization.bias", "./tensors/arg65.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.1.normalization.weight", "./tensors/arg66.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.1.convolution.weight", "./tensors/arg67.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.0.normalization.running_var", "./tensors/arg68.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.0.normalization.running_mean", "./tensors/arg69.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.0.normalization.bias", "./tensors/arg70.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.0.normalization.weight", "./tensors/arg71.tensorbin"),
    ("resnet.encoder.stages.0.layers.2.layer.0.convolution.weight", "./tensors/arg72.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.2.normalization.running_var", "./tensors/arg73.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.2.normalization.running_mean", "./tensors/arg74.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.2.normalization.bias", "./tensors/arg75.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.2.normalization.weight", "./tensors/arg76.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.2.convolution.weight", "./tensors/arg77.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.1.normalization.running_var", "./tensors/arg78.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.1.normalization.running_mean", "./tensors/arg79.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.1.normalization.bias", "./tensors/arg80.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.1.normalization.weight", "./tensors/arg81.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.1.convolution.weight", "./tensors/arg82.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.0.normalization.running_var", "./tensors/arg83.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.0.normalization.running_mean", "./tensors/arg84.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.0.normalization.bias", "./tensors/arg85.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.0.normalization.weight", "./tensors/arg86.tensorbin"),
    ("resnet.encoder.stages.1.layers.0.layer.0.convolution.weight", "./tensors/arg87.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.2.normalization.running_var", "./tensors/arg88.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.2.normalization.running_mean", "./tensors/arg89.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.2.normalization.bias", "./tensors/arg90.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.2.normalization.weight", "./tensors/arg91.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.2.convolution.weight", "./tensors/arg92.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.1.normalization.running_var", "./tensors/arg93.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.1.normalization.running_mean", "./tensors/arg94.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.1.normalization.bias", "./tensors/arg95.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.1.normalization.weight", "./tensors/arg96.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.1.convolution.weight", "./tensors/arg97.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.0.normalization.running_var", "./tensors/arg98.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.0.normalization.running_mean", "./tensors/arg99.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.0.normalization.bias", "./tensors/arg100.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.0.normalization.weight", "./tensors/arg101.tensorbin"),
    ("resnet.encoder.stages.1.layers.1.layer.0.convolution.weight", "./tensors/arg102.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.2.normalization.running_var", "./tensors/arg103.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.2.normalization.running_mean", "./tensors/arg104.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.2.normalization.bias", "./tensors/arg105.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.2.normalization.weight", "./tensors/arg106.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.2.convolution.weight", "./tensors/arg107.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.1.normalization.running_var", "./tensors/arg108.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.1.normalization.running_mean", "./tensors/arg109.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.1.normalization.bias", "./tensors/arg110.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.1.normalization.weight", "./tensors/arg111.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.1.convolution.weight", "./tensors/arg112.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.0.normalization.running_var", "./tensors/arg113.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.0.normalization.running_mean", "./tensors/arg114.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.0.normalization.bias", "./tensors/arg115.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.0.normalization.weight", "./tensors/arg116.tensorbin"),
    ("resnet.encoder.stages.1.layers.2.layer.0.convolution.weight", "./tensors/arg117.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.2.normalization.running_var", "./tensors/arg118.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.2.normalization.running_mean", "./tensors/arg119.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.2.normalization.bias", "./tensors/arg120.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.2.normalization.weight", "./tensors/arg121.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.2.convolution.weight", "./tensors/arg122.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.1.normalization.running_var", "./tensors/arg123.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.1.normalization.running_mean", "./tensors/arg124.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.1.normalization.bias", "./tensors/arg125.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.1.normalization.weight", "./tensors/arg126.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.1.convolution.weight", "./tensors/arg127.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.0.normalization.running_var", "./tensors/arg128.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.0.normalization.running_mean", "./tensors/arg129.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.0.normalization.bias", "./tensors/arg130.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.0.normalization.weight", "./tensors/arg131.tensorbin"),
    ("resnet.encoder.stages.1.layers.3.layer.0.convolution.weight", "./tensors/arg132.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.2.normalization.running_var", "./tensors/arg133.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.2.normalization.running_mean", "./tensors/arg134.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.2.normalization.bias", "./tensors/arg135.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.2.normalization.weight", "./tensors/arg136.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.2.convolution.weight", "./tensors/arg137.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.1.normalization.running_var", "./tensors/arg138.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.1.normalization.running_mean", "./tensors/arg139.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.1.normalization.bias", "./tensors/arg140.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.1.normalization.weight", "./tensors/arg141.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.1.convolution.weight", "./tensors/arg142.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.0.normalization.running_var", "./tensors/arg143.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.0.normalization.running_mean", "./tensors/arg144.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.0.normalization.bias", "./tensors/arg145.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.0.normalization.weight", "./tensors/arg146.tensorbin"),
    ("resnet.encoder.stages.2.layers.0.layer.0.convolution.weight", "./tensors/arg147.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.2.normalization.running_var", "./tensors/arg148.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.2.normalization.running_mean", "./tensors/arg149.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.2.normalization.bias", "./tensors/arg150.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.2.normalization.weight", "./tensors/arg151.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.2.convolution.weight", "./tensors/arg152.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.1.normalization.running_var", "./tensors/arg153.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.1.normalization.running_mean", "./tensors/arg154.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.1.normalization.bias", "./tensors/arg155.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.1.normalization.weight", "./tensors/arg156.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.1.convolution.weight", "./tensors/arg157.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.0.normalization.running_var", "./tensors/arg158.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.0.normalization.running_mean", "./tensors/arg159.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.0.normalization.bias", "./tensors/arg160.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.0.normalization.weight", "./tensors/arg161.tensorbin"),
    ("resnet.encoder.stages.2.layers.1.layer.0.convolution.weight", "./tensors/arg162.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.2.normalization.running_var", "./tensors/arg163.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.2.normalization.running_mean", "./tensors/arg164.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.2.normalization.bias", "./tensors/arg165.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.2.normalization.weight", "./tensors/arg166.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.2.convolution.weight", "./tensors/arg167.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.1.normalization.running_var", "./tensors/arg168.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.1.normalization.running_mean", "./tensors/arg169.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.1.normalization.bias", "./tensors/arg170.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.1.normalization.weight", "./tensors/arg171.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.1.convolution.weight", "./tensors/arg172.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.0.normalization.running_var", "./tensors/arg173.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.0.normalization.running_mean", "./tensors/arg174.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.0.normalization.bias", "./tensors/arg175.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.0.normalization.weight", "./tensors/arg176.tensorbin"),
    ("resnet.encoder.stages.2.layers.2.layer.0.convolution.weight", "./tensors/arg177.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.2.normalization.running_var", "./tensors/arg178.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.2.normalization.running_mean", "./tensors/arg179.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.2.normalization.bias", "./tensors/arg180.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.2.normalization.weight", "./tensors/arg181.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.2.convolution.weight", "./tensors/arg182.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.1.normalization.running_var", "./tensors/arg183.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.1.normalization.running_mean", "./tensors/arg184.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.1.normalization.bias", "./tensors/arg185.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.1.normalization.weight", "./tensors/arg186.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.1.convolution.weight", "./tensors/arg187.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.0.normalization.running_var", "./tensors/arg188.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.0.normalization.running_mean", "./tensors/arg189.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.0.normalization.bias", "./tensors/arg190.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.0.normalization.weight", "./tensors/arg191.tensorbin"),
    ("resnet.encoder.stages.2.layers.3.layer.0.convolution.weight", "./tensors/arg192.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.2.normalization.running_var", "./tensors/arg193.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.2.normalization.running_mean", "./tensors/arg194.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.2.normalization.bias", "./tensors/arg195.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.2.normalization.weight", "./tensors/arg196.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.2.convolution.weight", "./tensors/arg197.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.1.normalization.running_var", "./tensors/arg198.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.1.normalization.running_mean", "./tensors/arg199.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.1.normalization.bias", "./tensors/arg200.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.1.normalization.weight", "./tensors/arg201.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.1.convolution.weight", "./tensors/arg202.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.0.normalization.running_var", "./tensors/arg203.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.0.normalization.running_mean", "./tensors/arg204.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.0.normalization.bias", "./tensors/arg205.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.0.normalization.weight", "./tensors/arg206.tensorbin"),
    ("resnet.encoder.stages.2.layers.4.layer.0.convolution.weight", "./tensors/arg207.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.2.normalization.running_var", "./tensors/arg208.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.2.normalization.running_mean", "./tensors/arg209.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.2.normalization.bias", "./tensors/arg210.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.2.normalization.weight", "./tensors/arg211.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.2.convolution.weight", "./tensors/arg212.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.1.normalization.running_var", "./tensors/arg213.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.1.normalization.running_mean", "./tensors/arg214.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.1.normalization.bias", "./tensors/arg215.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.1.normalization.weight", "./tensors/arg216.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.1.convolution.weight", "./tensors/arg217.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.0.normalization.running_var", "./tensors/arg218.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.0.normalization.running_mean", "./tensors/arg219.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.0.normalization.bias", "./tensors/arg220.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.0.normalization.weight", "./tensors/arg221.tensorbin"),
    ("resnet.encoder.stages.2.layers.5.layer.0.convolution.weight", "./tensors/arg222.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.2.normalization.running_var", "./tensors/arg223.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.2.normalization.running_mean", "./tensors/arg224.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.2.normalization.bias", "./tensors/arg225.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.2.normalization.weight", "./tensors/arg226.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.2.convolution.weight", "./tensors/arg227.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.1.normalization.running_var", "./tensors/arg228.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.1.normalization.running_mean", "./tensors/arg229.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.1.normalization.bias", "./tensors/arg230.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.1.normalization.weight", "./tensors/arg231.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.1.convolution.weight", "./tensors/arg232.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.0.normalization.running_var", "./tensors/arg233.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.0.normalization.running_mean", "./tensors/arg234.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.0.normalization.bias", "./tensors/arg235.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.0.normalization.weight", "./tensors/arg236.tensorbin"),
    ("resnet.encoder.stages.3.layers.0.layer.0.convolution.weight", "./tensors/arg237.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.2.normalization.running_var", "./tensors/arg238.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.2.normalization.running_mean", "./tensors/arg239.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.2.normalization.bias", "./tensors/arg240.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.2.normalization.weight", "./tensors/arg241.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.2.convolution.weight", "./tensors/arg242.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.1.normalization.running_var", "./tensors/arg243.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.1.normalization.running_mean", "./tensors/arg244.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.1.normalization.bias", "./tensors/arg245.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.1.normalization.weight", "./tensors/arg246.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.1.convolution.weight", "./tensors/arg247.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.0.normalization.running_var", "./tensors/arg248.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.0.normalization.running_mean", "./tensors/arg249.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.0.normalization.bias", "./tensors/arg250.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.0.normalization.weight", "./tensors/arg251.tensorbin"),
    ("resnet.encoder.stages.3.layers.1.layer.0.convolution.weight", "./tensors/arg252.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.2.normalization.running_var", "./tensors/arg253.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.2.normalization.running_mean", "./tensors/arg254.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.2.normalization.bias", "./tensors/arg255.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.2.normalization.weight", "./tensors/arg256.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.2.convolution.weight", "./tensors/arg257.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.1.normalization.running_var", "./tensors/arg258.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.1.normalization.running_mean", "./tensors/arg259.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.1.normalization.bias", "./tensors/arg260.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.1.normalization.weight", "./tensors/arg261.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.1.convolution.weight", "./tensors/arg262.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.0.normalization.running_var", "./tensors/arg263.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.0.normalization.running_mean", "./tensors/arg264.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.0.normalization.bias", "./tensors/arg265.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.0.normalization.weight", "./tensors/arg266.tensorbin"),
    ("resnet.encoder.stages.3.layers.2.layer.0.convolution.weight", "./tensors/arg267.tensorbin"),
]

ALL_WEIGHT_NAMES = [name for name, _ in ALL_WEIGHTS]


_main_weights = {}


def load_weights_for__main():
    global _main_weights
    for name, file_path in ALL_WEIGHTS:
        _main_weights[name] = utils.load_tensor(
            file_path,
            ttnn.Layout.ROW_MAJOR,
            ttnn.DataType.BFLOAT16,
            None,
            None,
        )
    return _main_weights


def load_weights_for__main_from_state_dict():
    model = model_pt.load_pytorch_model()
    sd = dict(model.state_dict())
    for name, buf in model.named_buffers():
        if name not in sd:
            sd[name] = buf

    weights = {}
    for key in ALL_WEIGHT_NAMES:
        pt_tensor = sd[key]
        ttnn_tensor = ttnn.from_torch(pt_tensor)
        ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.ROW_MAJOR)
        ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.BFLOAT16)
        weights[key] = ttnn_tensor

    return weights
