# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
import ttnn
import utils
import model_pt


LAYERNORM_WEIGHTS = {
    "model.layers.0.input_layernorm.parametrizations.weight.original",
    "model.layers.0.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.1.input_layernorm.parametrizations.weight.original",
    "model.layers.1.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.10.input_layernorm.parametrizations.weight.original",
    "model.layers.10.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.11.input_layernorm.parametrizations.weight.original",
    "model.layers.11.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.12.input_layernorm.parametrizations.weight.original",
    "model.layers.12.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.13.input_layernorm.parametrizations.weight.original",
    "model.layers.13.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.14.input_layernorm.parametrizations.weight.original",
    "model.layers.14.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.15.input_layernorm.parametrizations.weight.original",
    "model.layers.15.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.16.input_layernorm.parametrizations.weight.original",
    "model.layers.16.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.17.input_layernorm.parametrizations.weight.original",
    "model.layers.17.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.18.input_layernorm.parametrizations.weight.original",
    "model.layers.18.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.19.input_layernorm.parametrizations.weight.original",
    "model.layers.19.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.2.input_layernorm.parametrizations.weight.original",
    "model.layers.2.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.20.input_layernorm.parametrizations.weight.original",
    "model.layers.20.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.21.input_layernorm.parametrizations.weight.original",
    "model.layers.21.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.22.input_layernorm.parametrizations.weight.original",
    "model.layers.22.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.23.input_layernorm.parametrizations.weight.original",
    "model.layers.23.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.24.input_layernorm.parametrizations.weight.original",
    "model.layers.24.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.25.input_layernorm.parametrizations.weight.original",
    "model.layers.25.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.26.input_layernorm.parametrizations.weight.original",
    "model.layers.26.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.27.input_layernorm.parametrizations.weight.original",
    "model.layers.27.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.28.input_layernorm.parametrizations.weight.original",
    "model.layers.28.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.29.input_layernorm.parametrizations.weight.original",
    "model.layers.29.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.3.input_layernorm.parametrizations.weight.original",
    "model.layers.3.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.30.input_layernorm.parametrizations.weight.original",
    "model.layers.30.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.31.input_layernorm.parametrizations.weight.original",
    "model.layers.31.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.4.input_layernorm.parametrizations.weight.original",
    "model.layers.4.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.5.input_layernorm.parametrizations.weight.original",
    "model.layers.5.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.6.input_layernorm.parametrizations.weight.original",
    "model.layers.6.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.7.input_layernorm.parametrizations.weight.original",
    "model.layers.7.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.8.input_layernorm.parametrizations.weight.original",
    "model.layers.8.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.9.input_layernorm.parametrizations.weight.original",
    "model.layers.9.post_attention_layernorm.parametrizations.weight.original",
    "model.norm.parametrizations.weight.original",
}


ALL_WEIGHTS = [
    "lm_head.parametrizations.weight.original",
    "model.embed_tokens.parametrizations.weight.original",
    "model.layers.0.input_layernorm.parametrizations.weight.original",
    "model.layers.0.mlp.down_proj.parametrizations.weight.original",
    "model.layers.0.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.0.mlp.up_proj.parametrizations.weight.original",
    "model.layers.0.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.0.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.0.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.0.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.0.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.1.input_layernorm.parametrizations.weight.original",
    "model.layers.1.mlp.down_proj.parametrizations.weight.original",
    "model.layers.1.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.1.mlp.up_proj.parametrizations.weight.original",
    "model.layers.1.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.1.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.1.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.1.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.1.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.10.input_layernorm.parametrizations.weight.original",
    "model.layers.10.mlp.down_proj.parametrizations.weight.original",
    "model.layers.10.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.10.mlp.up_proj.parametrizations.weight.original",
    "model.layers.10.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.10.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.10.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.10.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.10.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.11.input_layernorm.parametrizations.weight.original",
    "model.layers.11.mlp.down_proj.parametrizations.weight.original",
    "model.layers.11.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.11.mlp.up_proj.parametrizations.weight.original",
    "model.layers.11.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.11.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.11.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.11.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.11.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.12.input_layernorm.parametrizations.weight.original",
    "model.layers.12.mlp.down_proj.parametrizations.weight.original",
    "model.layers.12.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.12.mlp.up_proj.parametrizations.weight.original",
    "model.layers.12.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.12.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.12.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.12.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.12.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.13.input_layernorm.parametrizations.weight.original",
    "model.layers.13.mlp.down_proj.parametrizations.weight.original",
    "model.layers.13.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.13.mlp.up_proj.parametrizations.weight.original",
    "model.layers.13.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.13.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.13.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.13.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.13.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.14.input_layernorm.parametrizations.weight.original",
    "model.layers.14.mlp.down_proj.parametrizations.weight.original",
    "model.layers.14.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.14.mlp.up_proj.parametrizations.weight.original",
    "model.layers.14.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.14.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.14.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.14.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.14.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.15.input_layernorm.parametrizations.weight.original",
    "model.layers.15.mlp.down_proj.parametrizations.weight.original",
    "model.layers.15.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.15.mlp.up_proj.parametrizations.weight.original",
    "model.layers.15.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.15.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.15.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.15.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.15.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.16.input_layernorm.parametrizations.weight.original",
    "model.layers.16.mlp.down_proj.parametrizations.weight.original",
    "model.layers.16.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.16.mlp.up_proj.parametrizations.weight.original",
    "model.layers.16.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.16.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.16.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.16.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.16.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.17.input_layernorm.parametrizations.weight.original",
    "model.layers.17.mlp.down_proj.parametrizations.weight.original",
    "model.layers.17.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.17.mlp.up_proj.parametrizations.weight.original",
    "model.layers.17.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.17.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.17.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.17.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.17.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.18.input_layernorm.parametrizations.weight.original",
    "model.layers.18.mlp.down_proj.parametrizations.weight.original",
    "model.layers.18.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.18.mlp.up_proj.parametrizations.weight.original",
    "model.layers.18.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.18.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.18.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.18.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.18.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.19.input_layernorm.parametrizations.weight.original",
    "model.layers.19.mlp.down_proj.parametrizations.weight.original",
    "model.layers.19.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.19.mlp.up_proj.parametrizations.weight.original",
    "model.layers.19.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.19.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.19.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.19.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.19.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.2.input_layernorm.parametrizations.weight.original",
    "model.layers.2.mlp.down_proj.parametrizations.weight.original",
    "model.layers.2.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.2.mlp.up_proj.parametrizations.weight.original",
    "model.layers.2.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.2.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.2.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.2.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.2.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.20.input_layernorm.parametrizations.weight.original",
    "model.layers.20.mlp.down_proj.parametrizations.weight.original",
    "model.layers.20.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.20.mlp.up_proj.parametrizations.weight.original",
    "model.layers.20.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.20.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.20.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.20.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.20.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.21.input_layernorm.parametrizations.weight.original",
    "model.layers.21.mlp.down_proj.parametrizations.weight.original",
    "model.layers.21.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.21.mlp.up_proj.parametrizations.weight.original",
    "model.layers.21.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.21.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.21.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.21.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.21.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.22.input_layernorm.parametrizations.weight.original",
    "model.layers.22.mlp.down_proj.parametrizations.weight.original",
    "model.layers.22.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.22.mlp.up_proj.parametrizations.weight.original",
    "model.layers.22.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.22.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.22.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.22.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.22.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.23.input_layernorm.parametrizations.weight.original",
    "model.layers.23.mlp.down_proj.parametrizations.weight.original",
    "model.layers.23.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.23.mlp.up_proj.parametrizations.weight.original",
    "model.layers.23.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.23.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.23.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.23.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.23.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.24.input_layernorm.parametrizations.weight.original",
    "model.layers.24.mlp.down_proj.parametrizations.weight.original",
    "model.layers.24.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.24.mlp.up_proj.parametrizations.weight.original",
    "model.layers.24.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.24.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.24.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.24.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.24.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.25.input_layernorm.parametrizations.weight.original",
    "model.layers.25.mlp.down_proj.parametrizations.weight.original",
    "model.layers.25.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.25.mlp.up_proj.parametrizations.weight.original",
    "model.layers.25.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.25.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.25.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.25.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.25.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.26.input_layernorm.parametrizations.weight.original",
    "model.layers.26.mlp.down_proj.parametrizations.weight.original",
    "model.layers.26.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.26.mlp.up_proj.parametrizations.weight.original",
    "model.layers.26.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.26.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.26.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.26.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.26.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.27.input_layernorm.parametrizations.weight.original",
    "model.layers.27.mlp.down_proj.parametrizations.weight.original",
    "model.layers.27.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.27.mlp.up_proj.parametrizations.weight.original",
    "model.layers.27.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.27.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.27.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.27.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.27.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.28.input_layernorm.parametrizations.weight.original",
    "model.layers.28.mlp.down_proj.parametrizations.weight.original",
    "model.layers.28.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.28.mlp.up_proj.parametrizations.weight.original",
    "model.layers.28.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.28.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.28.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.28.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.28.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.29.input_layernorm.parametrizations.weight.original",
    "model.layers.29.mlp.down_proj.parametrizations.weight.original",
    "model.layers.29.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.29.mlp.up_proj.parametrizations.weight.original",
    "model.layers.29.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.29.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.29.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.29.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.29.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.3.input_layernorm.parametrizations.weight.original",
    "model.layers.3.mlp.down_proj.parametrizations.weight.original",
    "model.layers.3.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.3.mlp.up_proj.parametrizations.weight.original",
    "model.layers.3.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.3.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.3.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.3.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.3.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.30.input_layernorm.parametrizations.weight.original",
    "model.layers.30.mlp.down_proj.parametrizations.weight.original",
    "model.layers.30.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.30.mlp.up_proj.parametrizations.weight.original",
    "model.layers.30.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.30.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.30.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.30.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.30.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.31.input_layernorm.parametrizations.weight.original",
    "model.layers.31.mlp.down_proj.parametrizations.weight.original",
    "model.layers.31.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.31.mlp.up_proj.parametrizations.weight.original",
    "model.layers.31.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.31.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.31.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.31.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.31.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.4.input_layernorm.parametrizations.weight.original",
    "model.layers.4.mlp.down_proj.parametrizations.weight.original",
    "model.layers.4.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.4.mlp.up_proj.parametrizations.weight.original",
    "model.layers.4.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.4.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.4.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.4.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.4.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.5.input_layernorm.parametrizations.weight.original",
    "model.layers.5.mlp.down_proj.parametrizations.weight.original",
    "model.layers.5.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.5.mlp.up_proj.parametrizations.weight.original",
    "model.layers.5.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.5.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.5.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.5.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.5.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.6.input_layernorm.parametrizations.weight.original",
    "model.layers.6.mlp.down_proj.parametrizations.weight.original",
    "model.layers.6.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.6.mlp.up_proj.parametrizations.weight.original",
    "model.layers.6.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.6.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.6.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.6.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.6.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.7.input_layernorm.parametrizations.weight.original",
    "model.layers.7.mlp.down_proj.parametrizations.weight.original",
    "model.layers.7.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.7.mlp.up_proj.parametrizations.weight.original",
    "model.layers.7.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.7.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.7.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.7.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.7.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.8.input_layernorm.parametrizations.weight.original",
    "model.layers.8.mlp.down_proj.parametrizations.weight.original",
    "model.layers.8.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.8.mlp.up_proj.parametrizations.weight.original",
    "model.layers.8.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.8.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.8.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.8.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.8.self_attn.v_proj.parametrizations.weight.original",
    "model.layers.9.input_layernorm.parametrizations.weight.original",
    "model.layers.9.mlp.down_proj.parametrizations.weight.original",
    "model.layers.9.mlp.gate_proj.parametrizations.weight.original",
    "model.layers.9.mlp.up_proj.parametrizations.weight.original",
    "model.layers.9.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.9.self_attn.k_proj.parametrizations.weight.original",
    "model.layers.9.self_attn.o_proj.parametrizations.weight.original",
    "model.layers.9.self_attn.q_proj.parametrizations.weight.original",
    "model.layers.9.self_attn.v_proj.parametrizations.weight.original",
    "model.norm.parametrizations.weight.original",
    "model.rotary_emb.inv_freq",
]


def load_weights_for__main_from_state_dict():
    model = model_pt.load_pytorch_model()
    sd = dict(model.state_dict())
    for name, buf in model.named_buffers():
        if name not in sd:
            sd[name] = buf

    device = utils.DeviceGetter.get_device((1, 1))

    weights = {}
    for key in ALL_WEIGHTS:
        # ALL_WEIGHTS uses the parametrized names captured during tracing, where
        # the weight-dtype override registered a parametrization that renamed
        # "<module>.weight" -> "<module>.parametrizations.weight.original". The
        # freshly loaded model here has no such parametrization, so map back to
        # the plain parameter name. The ".original" tensor holds the raw weight,
        # so the values are identical. (Non-weight keys such as buffers have no
        # ".parametrizations.weight.original" suffix and pass through unchanged.)
        sd_key = key.replace(".parametrizations.weight.original", ".weight")
        ttnn_tensor = ttnn.from_torch(sd[sd_key])

        if key in LAYERNORM_WEIGHTS:
            ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.TILE)
            ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.BFLOAT16)
            ttnn_tensor = ttnn.to_device(ttnn_tensor, device, ttnn.DRAM_MEMORY_CONFIG)
        else:
            ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.ROW_MAJOR)
            ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.BFLOAT16)

        weights[key] = ttnn_tensor

    return weights
