# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0

import ttnn
import utils
import model_pt


_WEIGHT_FILE_MAP = {
    "model.rotary_emb.inv_freq": "./tensors/arg1.tensorbin",
    "model.layers.0.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg2.tensorbin",
    "model.layers.0.input_layernorm.parametrizations.weight.original": "./tensors/arg3.tensorbin",
    "model.embed_tokens.parametrizations.weight.original": "./tensors/arg5.tensorbin",
    "model.layers.0.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg8.tensorbin",
    "model.layers.1.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg11.tensorbin",
    "model.layers.1.input_layernorm.parametrizations.weight.original": "./tensors/arg12.tensorbin",
    "model.layers.0.mlp.down_proj.parametrizations.weight.original": "./tensors/arg13.tensorbin",
    "model.layers.0.mlp.up_proj.parametrizations.weight.original": "./tensors/arg14.tensorbin",
    "model.layers.0.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg15.tensorbin",
    "model.layers.0.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg16.tensorbin",
    "model.layers.0.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg18.tensorbin",
    "model.layers.0.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg19.tensorbin",
    "model.layers.1.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg22.tensorbin",
    "model.layers.2.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg25.tensorbin",
    "model.layers.2.input_layernorm.parametrizations.weight.original": "./tensors/arg26.tensorbin",
    "model.layers.1.mlp.down_proj.parametrizations.weight.original": "./tensors/arg27.tensorbin",
    "model.layers.1.mlp.up_proj.parametrizations.weight.original": "./tensors/arg28.tensorbin",
    "model.layers.1.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg29.tensorbin",
    "model.layers.1.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg30.tensorbin",
    "model.layers.1.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg31.tensorbin",
    "model.layers.1.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg32.tensorbin",
    "model.layers.2.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg35.tensorbin",
    "model.layers.3.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg38.tensorbin",
    "model.layers.3.input_layernorm.parametrizations.weight.original": "./tensors/arg39.tensorbin",
    "model.layers.2.mlp.down_proj.parametrizations.weight.original": "./tensors/arg40.tensorbin",
    "model.layers.2.mlp.up_proj.parametrizations.weight.original": "./tensors/arg41.tensorbin",
    "model.layers.2.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg42.tensorbin",
    "model.layers.2.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg43.tensorbin",
    "model.layers.2.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg44.tensorbin",
    "model.layers.2.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg45.tensorbin",
    "model.layers.3.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg48.tensorbin",
    "model.layers.4.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg51.tensorbin",
    "model.layers.4.input_layernorm.parametrizations.weight.original": "./tensors/arg52.tensorbin",
    "model.layers.3.mlp.down_proj.parametrizations.weight.original": "./tensors/arg53.tensorbin",
    "model.layers.3.mlp.up_proj.parametrizations.weight.original": "./tensors/arg54.tensorbin",
    "model.layers.3.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg55.tensorbin",
    "model.layers.3.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg56.tensorbin",
    "model.layers.3.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg57.tensorbin",
    "model.layers.3.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg58.tensorbin",
    "model.layers.4.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg61.tensorbin",
    "model.layers.5.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg64.tensorbin",
    "model.layers.5.input_layernorm.parametrizations.weight.original": "./tensors/arg65.tensorbin",
    "model.layers.4.mlp.down_proj.parametrizations.weight.original": "./tensors/arg66.tensorbin",
    "model.layers.4.mlp.up_proj.parametrizations.weight.original": "./tensors/arg67.tensorbin",
    "model.layers.4.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg68.tensorbin",
    "model.layers.4.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg69.tensorbin",
    "model.layers.4.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg70.tensorbin",
    "model.layers.4.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg71.tensorbin",
    "model.layers.5.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg74.tensorbin",
    "model.layers.6.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg77.tensorbin",
    "model.layers.6.input_layernorm.parametrizations.weight.original": "./tensors/arg78.tensorbin",
    "model.layers.5.mlp.down_proj.parametrizations.weight.original": "./tensors/arg79.tensorbin",
    "model.layers.5.mlp.up_proj.parametrizations.weight.original": "./tensors/arg80.tensorbin",
    "model.layers.5.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg81.tensorbin",
    "model.layers.5.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg82.tensorbin",
    "model.layers.5.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg83.tensorbin",
    "model.layers.5.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg84.tensorbin",
    "model.layers.6.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg87.tensorbin",
    "model.layers.7.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg90.tensorbin",
    "model.layers.7.input_layernorm.parametrizations.weight.original": "./tensors/arg91.tensorbin",
    "model.layers.6.mlp.down_proj.parametrizations.weight.original": "./tensors/arg92.tensorbin",
    "model.layers.6.mlp.up_proj.parametrizations.weight.original": "./tensors/arg93.tensorbin",
    "model.layers.6.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg94.tensorbin",
    "model.layers.6.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg95.tensorbin",
    "model.layers.6.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg96.tensorbin",
    "model.layers.6.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg97.tensorbin",
    "model.layers.7.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg100.tensorbin",
    "model.layers.8.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg103.tensorbin",
    "model.layers.8.input_layernorm.parametrizations.weight.original": "./tensors/arg104.tensorbin",
    "model.layers.7.mlp.down_proj.parametrizations.weight.original": "./tensors/arg105.tensorbin",
    "model.layers.7.mlp.up_proj.parametrizations.weight.original": "./tensors/arg106.tensorbin",
    "model.layers.7.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg107.tensorbin",
    "model.layers.7.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg108.tensorbin",
    "model.layers.7.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg109.tensorbin",
    "model.layers.7.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg110.tensorbin",
    "model.layers.8.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg113.tensorbin",
    "model.layers.9.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg116.tensorbin",
    "model.layers.9.input_layernorm.parametrizations.weight.original": "./tensors/arg117.tensorbin",
    "model.layers.8.mlp.down_proj.parametrizations.weight.original": "./tensors/arg118.tensorbin",
    "model.layers.8.mlp.up_proj.parametrizations.weight.original": "./tensors/arg119.tensorbin",
    "model.layers.8.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg120.tensorbin",
    "model.layers.8.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg121.tensorbin",
    "model.layers.8.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg122.tensorbin",
    "model.layers.8.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg123.tensorbin",
    "model.layers.9.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg126.tensorbin",
    "model.layers.10.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg129.tensorbin",
    "model.layers.10.input_layernorm.parametrizations.weight.original": "./tensors/arg130.tensorbin",
    "model.layers.9.mlp.down_proj.parametrizations.weight.original": "./tensors/arg131.tensorbin",
    "model.layers.9.mlp.up_proj.parametrizations.weight.original": "./tensors/arg132.tensorbin",
    "model.layers.9.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg133.tensorbin",
    "model.layers.9.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg134.tensorbin",
    "model.layers.9.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg135.tensorbin",
    "model.layers.9.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg136.tensorbin",
    "model.layers.10.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg139.tensorbin",
    "model.layers.11.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg142.tensorbin",
    "model.layers.11.input_layernorm.parametrizations.weight.original": "./tensors/arg143.tensorbin",
    "model.layers.10.mlp.down_proj.parametrizations.weight.original": "./tensors/arg144.tensorbin",
    "model.layers.10.mlp.up_proj.parametrizations.weight.original": "./tensors/arg145.tensorbin",
    "model.layers.10.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg146.tensorbin",
    "model.layers.10.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg147.tensorbin",
    "model.layers.10.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg148.tensorbin",
    "model.layers.10.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg149.tensorbin",
    "model.layers.11.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg152.tensorbin",
    "model.layers.12.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg155.tensorbin",
    "model.layers.12.input_layernorm.parametrizations.weight.original": "./tensors/arg156.tensorbin",
    "model.layers.11.mlp.down_proj.parametrizations.weight.original": "./tensors/arg157.tensorbin",
    "model.layers.11.mlp.up_proj.parametrizations.weight.original": "./tensors/arg158.tensorbin",
    "model.layers.11.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg159.tensorbin",
    "model.layers.11.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg160.tensorbin",
    "model.layers.11.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg161.tensorbin",
    "model.layers.11.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg162.tensorbin",
    "model.layers.12.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg165.tensorbin",
    "model.layers.13.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg168.tensorbin",
    "model.layers.13.input_layernorm.parametrizations.weight.original": "./tensors/arg169.tensorbin",
    "model.layers.12.mlp.down_proj.parametrizations.weight.original": "./tensors/arg170.tensorbin",
    "model.layers.12.mlp.up_proj.parametrizations.weight.original": "./tensors/arg171.tensorbin",
    "model.layers.12.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg172.tensorbin",
    "model.layers.12.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg173.tensorbin",
    "model.layers.12.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg174.tensorbin",
    "model.layers.12.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg175.tensorbin",
    "model.layers.13.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg178.tensorbin",
    "model.layers.14.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg181.tensorbin",
    "model.layers.14.input_layernorm.parametrizations.weight.original": "./tensors/arg182.tensorbin",
    "model.layers.13.mlp.down_proj.parametrizations.weight.original": "./tensors/arg183.tensorbin",
    "model.layers.13.mlp.up_proj.parametrizations.weight.original": "./tensors/arg184.tensorbin",
    "model.layers.13.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg185.tensorbin",
    "model.layers.13.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg186.tensorbin",
    "model.layers.13.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg187.tensorbin",
    "model.layers.13.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg188.tensorbin",
    "model.layers.14.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg191.tensorbin",
    "model.layers.15.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg194.tensorbin",
    "model.layers.15.input_layernorm.parametrizations.weight.original": "./tensors/arg195.tensorbin",
    "model.layers.14.mlp.down_proj.parametrizations.weight.original": "./tensors/arg196.tensorbin",
    "model.layers.14.mlp.up_proj.parametrizations.weight.original": "./tensors/arg197.tensorbin",
    "model.layers.14.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg198.tensorbin",
    "model.layers.14.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg199.tensorbin",
    "model.layers.14.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg200.tensorbin",
    "model.layers.14.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg201.tensorbin",
    "model.layers.15.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg204.tensorbin",
    "model.layers.16.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg207.tensorbin",
    "model.layers.16.input_layernorm.parametrizations.weight.original": "./tensors/arg208.tensorbin",
    "model.layers.15.mlp.down_proj.parametrizations.weight.original": "./tensors/arg209.tensorbin",
    "model.layers.15.mlp.up_proj.parametrizations.weight.original": "./tensors/arg210.tensorbin",
    "model.layers.15.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg211.tensorbin",
    "model.layers.15.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg212.tensorbin",
    "model.layers.15.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg213.tensorbin",
    "model.layers.15.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg214.tensorbin",
    "model.layers.16.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg217.tensorbin",
    "model.layers.17.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg220.tensorbin",
    "model.layers.17.input_layernorm.parametrizations.weight.original": "./tensors/arg221.tensorbin",
    "model.layers.16.mlp.down_proj.parametrizations.weight.original": "./tensors/arg222.tensorbin",
    "model.layers.16.mlp.up_proj.parametrizations.weight.original": "./tensors/arg223.tensorbin",
    "model.layers.16.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg224.tensorbin",
    "model.layers.16.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg225.tensorbin",
    "model.layers.16.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg226.tensorbin",
    "model.layers.16.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg227.tensorbin",
    "model.layers.17.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg230.tensorbin",
    "model.layers.18.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg233.tensorbin",
    "model.layers.18.input_layernorm.parametrizations.weight.original": "./tensors/arg234.tensorbin",
    "model.layers.17.mlp.down_proj.parametrizations.weight.original": "./tensors/arg235.tensorbin",
    "model.layers.17.mlp.up_proj.parametrizations.weight.original": "./tensors/arg236.tensorbin",
    "model.layers.17.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg237.tensorbin",
    "model.layers.17.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg238.tensorbin",
    "model.layers.17.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg239.tensorbin",
    "model.layers.17.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg240.tensorbin",
    "model.layers.18.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg243.tensorbin",
    "model.layers.19.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg246.tensorbin",
    "model.layers.19.input_layernorm.parametrizations.weight.original": "./tensors/arg247.tensorbin",
    "model.layers.18.mlp.down_proj.parametrizations.weight.original": "./tensors/arg248.tensorbin",
    "model.layers.18.mlp.up_proj.parametrizations.weight.original": "./tensors/arg249.tensorbin",
    "model.layers.18.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg250.tensorbin",
    "model.layers.18.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg251.tensorbin",
    "model.layers.18.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg252.tensorbin",
    "model.layers.18.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg253.tensorbin",
    "model.layers.19.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg256.tensorbin",
    "model.layers.20.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg259.tensorbin",
    "model.layers.20.input_layernorm.parametrizations.weight.original": "./tensors/arg260.tensorbin",
    "model.layers.19.mlp.down_proj.parametrizations.weight.original": "./tensors/arg261.tensorbin",
    "model.layers.19.mlp.up_proj.parametrizations.weight.original": "./tensors/arg262.tensorbin",
    "model.layers.19.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg263.tensorbin",
    "model.layers.19.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg264.tensorbin",
    "model.layers.19.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg265.tensorbin",
    "model.layers.19.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg266.tensorbin",
    "model.layers.20.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg269.tensorbin",
    "model.layers.21.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg272.tensorbin",
    "model.layers.21.input_layernorm.parametrizations.weight.original": "./tensors/arg273.tensorbin",
    "model.layers.20.mlp.down_proj.parametrizations.weight.original": "./tensors/arg274.tensorbin",
    "model.layers.20.mlp.up_proj.parametrizations.weight.original": "./tensors/arg275.tensorbin",
    "model.layers.20.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg276.tensorbin",
    "model.layers.20.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg277.tensorbin",
    "model.layers.20.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg278.tensorbin",
    "model.layers.20.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg279.tensorbin",
    "model.layers.21.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg282.tensorbin",
    "model.layers.22.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg285.tensorbin",
    "model.layers.22.input_layernorm.parametrizations.weight.original": "./tensors/arg286.tensorbin",
    "model.layers.21.mlp.down_proj.parametrizations.weight.original": "./tensors/arg287.tensorbin",
    "model.layers.21.mlp.up_proj.parametrizations.weight.original": "./tensors/arg288.tensorbin",
    "model.layers.21.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg289.tensorbin",
    "model.layers.21.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg290.tensorbin",
    "model.layers.21.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg291.tensorbin",
    "model.layers.21.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg292.tensorbin",
    "model.layers.22.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg295.tensorbin",
    "model.layers.23.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg298.tensorbin",
    "model.layers.23.input_layernorm.parametrizations.weight.original": "./tensors/arg299.tensorbin",
    "model.layers.22.mlp.down_proj.parametrizations.weight.original": "./tensors/arg300.tensorbin",
    "model.layers.22.mlp.up_proj.parametrizations.weight.original": "./tensors/arg301.tensorbin",
    "model.layers.22.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg302.tensorbin",
    "model.layers.22.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg303.tensorbin",
    "model.layers.22.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg304.tensorbin",
    "model.layers.22.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg305.tensorbin",
    "model.layers.23.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg308.tensorbin",
    "model.layers.24.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg311.tensorbin",
    "model.layers.24.input_layernorm.parametrizations.weight.original": "./tensors/arg312.tensorbin",
    "model.layers.23.mlp.down_proj.parametrizations.weight.original": "./tensors/arg313.tensorbin",
    "model.layers.23.mlp.up_proj.parametrizations.weight.original": "./tensors/arg314.tensorbin",
    "model.layers.23.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg315.tensorbin",
    "model.layers.23.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg316.tensorbin",
    "model.layers.23.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg317.tensorbin",
    "model.layers.23.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg318.tensorbin",
    "model.layers.24.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg321.tensorbin",
    "model.layers.25.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg324.tensorbin",
    "model.layers.25.input_layernorm.parametrizations.weight.original": "./tensors/arg325.tensorbin",
    "model.layers.24.mlp.down_proj.parametrizations.weight.original": "./tensors/arg326.tensorbin",
    "model.layers.24.mlp.up_proj.parametrizations.weight.original": "./tensors/arg327.tensorbin",
    "model.layers.24.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg328.tensorbin",
    "model.layers.24.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg329.tensorbin",
    "model.layers.24.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg330.tensorbin",
    "model.layers.24.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg331.tensorbin",
    "model.layers.25.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg334.tensorbin",
    "model.layers.26.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg337.tensorbin",
    "model.layers.26.input_layernorm.parametrizations.weight.original": "./tensors/arg338.tensorbin",
    "model.layers.25.mlp.down_proj.parametrizations.weight.original": "./tensors/arg339.tensorbin",
    "model.layers.25.mlp.up_proj.parametrizations.weight.original": "./tensors/arg340.tensorbin",
    "model.layers.25.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg341.tensorbin",
    "model.layers.25.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg342.tensorbin",
    "model.layers.25.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg343.tensorbin",
    "model.layers.25.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg344.tensorbin",
    "model.layers.26.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg347.tensorbin",
    "model.layers.27.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg350.tensorbin",
    "model.layers.27.input_layernorm.parametrizations.weight.original": "./tensors/arg351.tensorbin",
    "model.layers.26.mlp.down_proj.parametrizations.weight.original": "./tensors/arg352.tensorbin",
    "model.layers.26.mlp.up_proj.parametrizations.weight.original": "./tensors/arg353.tensorbin",
    "model.layers.26.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg354.tensorbin",
    "model.layers.26.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg355.tensorbin",
    "model.layers.26.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg356.tensorbin",
    "model.layers.26.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg357.tensorbin",
    "model.layers.27.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg360.tensorbin",
    "model.layers.28.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg363.tensorbin",
    "model.layers.28.input_layernorm.parametrizations.weight.original": "./tensors/arg364.tensorbin",
    "model.layers.27.mlp.down_proj.parametrizations.weight.original": "./tensors/arg365.tensorbin",
    "model.layers.27.mlp.up_proj.parametrizations.weight.original": "./tensors/arg366.tensorbin",
    "model.layers.27.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg367.tensorbin",
    "model.layers.27.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg368.tensorbin",
    "model.layers.27.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg369.tensorbin",
    "model.layers.27.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg370.tensorbin",
    "model.layers.28.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg373.tensorbin",
    "model.layers.29.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg376.tensorbin",
    "model.layers.29.input_layernorm.parametrizations.weight.original": "./tensors/arg377.tensorbin",
    "model.layers.28.mlp.down_proj.parametrizations.weight.original": "./tensors/arg378.tensorbin",
    "model.layers.28.mlp.up_proj.parametrizations.weight.original": "./tensors/arg379.tensorbin",
    "model.layers.28.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg380.tensorbin",
    "model.layers.28.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg381.tensorbin",
    "model.layers.28.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg382.tensorbin",
    "model.layers.28.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg383.tensorbin",
    "model.layers.29.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg386.tensorbin",
    "model.layers.30.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg389.tensorbin",
    "model.layers.30.input_layernorm.parametrizations.weight.original": "./tensors/arg390.tensorbin",
    "model.layers.29.mlp.down_proj.parametrizations.weight.original": "./tensors/arg391.tensorbin",
    "model.layers.29.mlp.up_proj.parametrizations.weight.original": "./tensors/arg392.tensorbin",
    "model.layers.29.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg393.tensorbin",
    "model.layers.29.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg394.tensorbin",
    "model.layers.29.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg395.tensorbin",
    "model.layers.29.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg396.tensorbin",
    "model.layers.30.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg399.tensorbin",
    "model.layers.31.self_attn.k_proj.parametrizations.weight.original": "./tensors/arg402.tensorbin",
    "model.layers.31.input_layernorm.parametrizations.weight.original": "./tensors/arg403.tensorbin",
    "model.layers.30.mlp.down_proj.parametrizations.weight.original": "./tensors/arg404.tensorbin",
    "model.layers.30.mlp.up_proj.parametrizations.weight.original": "./tensors/arg405.tensorbin",
    "model.layers.30.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg406.tensorbin",
    "model.layers.30.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg407.tensorbin",
    "model.layers.30.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg408.tensorbin",
    "model.layers.30.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg409.tensorbin",
    "model.layers.31.self_attn.v_proj.parametrizations.weight.original": "./tensors/arg412.tensorbin",
    "lm_head.parametrizations.weight.original": "./tensors/arg415.tensorbin",
    "model.norm.parametrizations.weight.original": "./tensors/arg416.tensorbin",
    "model.layers.31.mlp.down_proj.parametrizations.weight.original": "./tensors/arg417.tensorbin",
    "model.layers.31.mlp.up_proj.parametrizations.weight.original": "./tensors/arg418.tensorbin",
    "model.layers.31.post_attention_layernorm.parametrizations.weight.original": "./tensors/arg419.tensorbin",
    "model.layers.31.self_attn.o_proj.parametrizations.weight.original": "./tensors/arg420.tensorbin",
    "model.layers.31.self_attn.q_proj.parametrizations.weight.original": "./tensors/arg421.tensorbin",
    "model.layers.31.mlp.gate_proj.parametrizations.weight.original": "./tensors/arg422.tensorbin",
}

LAYERNORM_WEIGHTS = {
    "model.layers.0.input_layernorm.parametrizations.weight.original",
    "model.layers.0.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.1.input_layernorm.parametrizations.weight.original",
    "model.layers.1.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.10.input_layernorm.parametrizations.weight.original",
    "model.layers.10.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.11.input_layernorm.parametrizations.weight.original",
    "model.layers.11.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.12.input_layernorm.parametrizations.weight.original",
    "model.layers.12.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.13.input_layernorm.parametrizations.weight.original",
    "model.layers.13.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.14.input_layernorm.parametrizations.weight.original",
    "model.layers.14.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.15.input_layernorm.parametrizations.weight.original",
    "model.layers.15.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.16.input_layernorm.parametrizations.weight.original",
    "model.layers.16.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.17.input_layernorm.parametrizations.weight.original",
    "model.layers.17.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.18.input_layernorm.parametrizations.weight.original",
    "model.layers.18.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.19.input_layernorm.parametrizations.weight.original",
    "model.layers.19.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.2.input_layernorm.parametrizations.weight.original",
    "model.layers.2.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.20.input_layernorm.parametrizations.weight.original",
    "model.layers.20.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.21.input_layernorm.parametrizations.weight.original",
    "model.layers.21.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.22.input_layernorm.parametrizations.weight.original",
    "model.layers.22.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.23.input_layernorm.parametrizations.weight.original",
    "model.layers.23.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.24.input_layernorm.parametrizations.weight.original",
    "model.layers.24.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.25.input_layernorm.parametrizations.weight.original",
    "model.layers.25.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.26.input_layernorm.parametrizations.weight.original",
    "model.layers.26.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.27.input_layernorm.parametrizations.weight.original",
    "model.layers.27.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.28.input_layernorm.parametrizations.weight.original",
    "model.layers.28.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.29.input_layernorm.parametrizations.weight.original",
    "model.layers.29.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.3.input_layernorm.parametrizations.weight.original",
    "model.layers.3.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.30.input_layernorm.parametrizations.weight.original",
    "model.layers.30.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.31.input_layernorm.parametrizations.weight.original",
    "model.layers.31.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.4.input_layernorm.parametrizations.weight.original",
    "model.layers.4.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.5.input_layernorm.parametrizations.weight.original",
    "model.layers.5.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.6.input_layernorm.parametrizations.weight.original",
    "model.layers.6.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.7.input_layernorm.parametrizations.weight.original",
    "model.layers.7.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.8.input_layernorm.parametrizations.weight.original",
    "model.layers.8.post_attention_layernorm.parametrizations.weight.original",
    "model.layers.9.input_layernorm.parametrizations.weight.original",
    "model.layers.9.post_attention_layernorm.parametrizations.weight.original",
    "model.norm.parametrizations.weight.original",
}

ALL_WEIGHTS = tuple(_WEIGHT_FILE_MAP.keys())


def load_weights_for__main():
    device = utils.DeviceGetter.get_device((1, 1))
    weights = {}
    for key, file_path in _WEIGHT_FILE_MAP.items():
        if key in LAYERNORM_WEIGHTS:
            weights[key] = utils.load_tensor(
                file_path,
                ttnn.Layout.TILE,
                ttnn.DataType.BFLOAT16,
                device,
                ttnn.MemoryConfig(
                    ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM, None
                ),
            )
        else:
            weights[key] = utils.load_tensor(
                file_path,
                ttnn.Layout.ROW_MAJOR,
                ttnn.DataType.BFLOAT16,
                None,
                None,
            )
    return weights


def load_weights_for__main_from_state_dict():
    model = model_pt.load_pytorch_model()
    sd = dict(model.state_dict())
    for name, buf in model.named_buffers():
        if name not in sd:
            sd[name] = buf

    device = utils.DeviceGetter.get_device((1, 1))
    weights = {}
    for key in ALL_WEIGHTS:
        pt_tensor = sd[key]
        ttnn_tensor = ttnn.from_torch(pt_tensor)

        if key in LAYERNORM_WEIGHTS:
            ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.TILE)
            ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.BFLOAT16)
            ttnn_tensor = ttnn.to_device(ttnn_tensor, device, ttnn.DRAM_MEMORY_CONFIG)
        else:
            ttnn_tensor = ttnn.to_layout(ttnn_tensor, ttnn.Layout.ROW_MAJOR)
            ttnn_tensor = ttnn.to_dtype(ttnn_tensor, ttnn.DataType.BFLOAT16)

        weights[key] = ttnn_tensor
    return weights
